//Autogenerated
import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class AddressInputLocalizer extends BaseComponentLocalizer {

    //Constants


    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "fi", label: "Suomi" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська (Україна)" }
            ],
            "en");
        
        //Initializer

    }


}

//Singleton
export default new AddressInputLocalizer();