options:
  docker: true

pipelines:
  branches:
    master: # Pipelines that will be triggered automatically
      - parallel:
          - step:
              name: Extensions build
              image: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
              size: 2x # Double resources available for this step.
              script:
                - dotnet pack -p:PackageVersion=1.0-${BITBUCKET_BUILD_NUMBER} ./Renta.Extensions/Renta.Extensions.csproj
                - nuget push ./Renta.Extensions/bin/Debug/RentaExtensions.1.0-${BITBUCKET_BUILD_NUMBER}.nupkg ${MYGET_API_KEY} -Source https://www.myget.org/F/renta-dotnet-extensions/api/v2/package
              services:
                - docker
              caches:
                - dotnetcore
definitions:
  caches:
    dotnetcore: ~/.nuget/packages
  services:
    docker:
      memory: 2048
