//Autogenerated

import {BaseComponentLocalizer} from "@weare/reapptor-react-common";

class QrWidgetLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly scanErrorLanguageItemName: string = `Scan.Error`;

    constructor() {

        super(
            [
                { code: "en", label: "English", isLanguage: true },
                { code: "da", label: "Dansk", isLanguage: true },
                { code: "fi", label: "Suomi", isLanguage: true },
                { code: "nb", label: "Norsk bokmål", isLanguage: true },
                { code: "pl", label: "Polski", isLanguage: true },
                { code: "ru", label: "Русский", isLanguage: true },
                { code: "sv", label: "Svenska", isLanguage: true },
                { code: "uk", label: "Українська", isLanguage: true }
            ],
            "en");
        
        //Initializer
        this.set(this.scanErrorLanguageItemName, { language: `en`, value: `QR code scanner is not available, probably no permissions to camera on your mobile device.` }, { language: `uk`, value: `Сканер QR-коду недоступний, можливо, на вашому мобільному пристрої не отримано дозволу на використання камери.` }, { language: `sv`, value: `QR-kodskanner inte tillgänglig, förmodligen inga behörigheter för kameran på din mobila enhet.` }, { language: `ru`, value: `Сканер QR-кода недоступен, возможно, на вашем мобильном устройстве не получено разрешение на использование камеры.` }, { language: `pl`, value: `Skaner kodów QR niedostępny, prawdopodobnie brak uprawnień do kamery na Twoim urządzeniu mobilnym.` }, { language: `nb`, value: `QR-kodeskanner er ikke tilgjengelig, det er sannsynligvis ingen tillatelser til bruk av kamera på mobilenheten din.` }, { language: `fi`, value: `QR koodi skanneri ei käytössä. Mahdollisesti kameran käyttöoikeudet puuttuvat laitteeltasi.` }, { language: `da`, value: `QR-kodescanner er ikke tilgængelig, sandsynligvis ingen tilladelser til kameraet på din mobile enhed.` },);
    }

    /**
    /* "Scan.Error" (QR code scanner is not available, probably no permissions to camera on your mobile device.)
    */
    public get scanError() : string {
        return this.get(this.scanErrorLanguageItemName);
    }
}

//Singleton
export default new QrWidgetLocalizer();