//Autogenerated

import {Language} from "@weare/reapptor-toolkit";
import {BaseComponentLocalizer} from "@weare/reapptor-react-common";

class QrWidgetLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly scanErrorLanguageItemName: string = `Scan.Error`;

    constructor() {

        super(
            [
                new Language("en", "English"),
                new Language("da", "Dansk"),
                new Language("fi", "Suomi"),
                new Language("nb", "Norsk bokmål"),
                new Language("pl", "Polski"),
                new Language("ru", "Русский"),
                new Language("sv", "Svenska"),
                new Language("uk", "Українська")
            ],
            "en");
        
        //Initializer
        this.set(this.scanErrorLanguageItemName, { language: `en`, value: `QR code scanner is not available, probably no permissions to camera on your mobile device.` }, { language: `uk`, value: `Сканер QR-коду недоступний, можливо, на вашому мобільному пристрої не отримано дозволу на використання камери.` }, { language: `sv`, value: `QR-kodskanner inte tillgänglig, förmodligen inga behörigheter för kameran på din mobila enhet.` }, { language: `ru`, value: `Сканер QR-кода недоступен, возможно, на вашем мобильном устройстве не получено разрешение на использование камеры.` }, { language: `pl`, value: `Skaner kodów QR niedostępny, prawdopodobnie brak uprawnień do kamery na Twoim urządzeniu mobilnym.` }, { language: `nb`, value: `QR-kodeskanner er ikke tilgjengelig, det er sannsynligvis ingen tillatelser til bruk av kamera på mobilenheten din.` }, { language: `fi`, value: `QR koodi skanneri ei käytössä. Mahdollisesti kameran käyttöoikeudet puuttuvat laitteeltasi.` }, { language: `da`, value: `QR-kodescanner er ikke tilgængelig, sandsynligvis ingen tilladelser til kameraet på din mobile enhed.` },);
    }

    /**
    /* "Scan.Error" (QR code scanner is not available, probably no permissions to camera on your mobile device.)
    */
    public get scanError() : string {
        return this.get(this.scanErrorLanguageItemName);
    }
}

//Singleton
export default new QrWidgetLocalizer();