//Autogenerated

import {Language} from "@weare/reapptor-toolkit";
import {BaseComponentLocalizer} from "@weare/reapptor-react-common";

class PasswordInputLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly helpTextLengthLanguageItemName: string = `HelpText.Length`;

    constructor() {

        super(
            [
                new Language("en", "English"),
                new Language("da", "Dansk"),
                new Language("fi", "Suomi"),
                new Language("nb", "Norsk bokmål"),
                new Language("pl", "Polski"),
                new Language("ru", "Русский"),
                new Language("sv", "Svenska"),
                new Language("uk", "Українська")
            ],
            "en");
        
        //Initializer
        this.set(this.helpTextLengthLanguageItemName, { language: `en`, value: `at least 8 characters long` }, { language: `uk`, value: `Не менше 8 символів` }, { language: `sv`, value: `åtminstone 8 tecken` }, { language: `ru`, value: `не менее 8 символов` }, { language: `pl`, value: `Co najmniej 8 znaków` }, { language: `nb`, value: `Minst 8 tegn` }, { language: `fi`, value: `vähintään 8 merkkiä` }, { language: `da`, value: `Mindst 8 tegn lang` },);
    }

    /**
    /* "HelpText.Length" (at least 8 characters long)
    */
    public get helpTextLength() : string {
        return this.get(this.helpTextLengthLanguageItemName);
    }
}

//Singleton
export default new PasswordInputLocalizer();