//Autogenerated

import {BaseComponentLocalizer} from "@weare/reapptor-react-common";

class QrInputLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly buttonCloseLanguageItemName: string = `Button.Close`;
    public readonly buttonLabelLanguageItemName: string = `Button.Label`;

    constructor() {

        super(
            [
                { code: "en", label: "English", isLanguage: true },
                { code: "da", label: "Dansk", isLanguage: true },
                { code: "fi", label: "Suomi", isLanguage: true },
                { code: "nb", label: "Norsk bokmål", isLanguage: true },
                { code: "pl", label: "Polski", isLanguage: true },
                { code: "ru", label: "Русский", isLanguage: true },
                { code: "sv", label: "Svenska", isLanguage: true },
                { code: "uk", label: "Українська", isLanguage: true }
            ],
            "en");
        
        //Initializer
        this.set(this.buttonCloseLanguageItemName, { language: `en`, value: `Close` }, { language: `uk`, value: `\nЗакрити` }, { language: `sv`, value: `Stänga` }, { language: `ru`, value: `Закрывать` }, { language: `pl`, value: `\nBlisko` }, { language: `nb`, value: `Lukk` }, { language: `fi`, value: `Sulje` }, { language: `da`, value: `Tæt` },);
        this.set(this.buttonLabelLanguageItemName, { language: `en`, value: `Qr code` }, { language: `sv`, value: `Qr-kod` }, { language: `pl`, value: `Kod Qr` }, { language: `nb`, value: `QR kode` }, { language: `fi`, value: `Qr-koodi` }, { language: `da`, value: `Qr-kode` },);
    }

    /**
    /* "Button.Close" (Close)
    */
    public get buttonClose() : string {
        return this.get(this.buttonCloseLanguageItemName);
    }

    /**
    /* "Button.Label" (Qr code)
    */
    public get buttonLabel() : string {
        return this.get(this.buttonLabelLanguageItemName);
    }
}

//Singleton
export default new QrInputLocalizer();