//Autogenerated

import {Language} from "@weare/reapptor-toolkit";
import {BaseComponentLocalizer} from "@weare/reapptor-react-common";

class QrInputLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly buttonCloseLanguageItemName: string = `Button.Close`;
    public readonly buttonLabelLanguageItemName: string = `Button.Label`;

    constructor() {

        super(
            [
                new Language("en", "English"),
                new Language("da", "Dansk"),
                new Language("fi", "Suomi"),
                new Language("nb", "Norsk bokmål"),
                new Language("pl", "Polski"),
                new Language("ru", "Русский"),
                new Language("sv", "Svenska"),
                new Language("uk", "Українська")
            ],
            "en");
        
        //Initializer
        this.set(this.buttonCloseLanguageItemName, { language: `en`, value: `Close` }, { language: `uk`, value: `\nЗакрити` }, { language: `sv`, value: `Stänga` }, { language: `ru`, value: `Закрывать` }, { language: `pl`, value: `\nBlisko` }, { language: `nb`, value: `Lukk` }, { language: `fi`, value: `Sulje` }, { language: `da`, value: `Tæt` },);
        this.set(this.buttonLabelLanguageItemName, { language: `en`, value: `Qr code` }, { language: `sv`, value: `Qr-kod` }, { language: `pl`, value: `Kod Qr` }, { language: `nb`, value: `QR kode` }, { language: `fi`, value: `Qr-koodi` }, { language: `da`, value: `Qr-kode` },);
    }

    /**
    /* "Button.Close" (Close)
    */
    public get buttonClose() : string {
        return this.get(this.buttonCloseLanguageItemName);
    }

    /**
    /* "Button.Label" (Qr code)
    */
    public get buttonLabel() : string {
        return this.get(this.buttonLabelLanguageItemName);
    }
}

//Singleton
export default new QrInputLocalizer();