//Autogenerated

import {BaseComponentsLocalizer} from "@weare/athenaeum-react-common";

class ComponentsLocalizer extends BaseComponentsLocalizer {

    //Constants
    public readonly dropdownMultipleSelectedLanguageItemName: string = `Dropdown.MultipleSelected`;
    public readonly listLoadingLanguageItemName: string = `List.Loading`;
    public readonly signatureWidgetClearLanguageItemName: string = `SignatureWidget.Clear`;
    public readonly signatureWidgetDoneLanguageItemName: string = `SignatureWidget.Done`;
    public readonly modalSaveChangesLanguageItemName: string = `Modal.SaveChanges`;
    public readonly modalCloseLanguageItemName: string = `Modal.Close`;
    public readonly pageContainerPageHelpLanguageItemName: string = `PageContainer.PageHelp`;
    public readonly navigationWidgetPreviousLanguageItemName: string = `NavigationWidget.Previous`;
    public readonly navigationWidgetReturnToPreviousLanguageItemName: string = `NavigationWidget.ReturnToPrevious`;
    public readonly navigationWidgetNextLanguageItemName: string = `NavigationWidget.Next`;
    public readonly navigationWidgetGoToNextLanguageItemName: string = `NavigationWidget.GoToNext`;
    public readonly confirmationDialogAreYouSureLanguageItemName: string = `ConfirmationDialog.AreYouSure`;
    public readonly confirmationDialogConfirmButtonLanguageItemName: string = `ConfirmationDialog.ConfirmButton`;
    public readonly confirmationDialogCloseButtonLanguageItemName: string = `ConfirmationDialog.CloseButton`;
    public readonly confirmationDialogCommentLanguageItemName: string = `ConfirmationDialog.Comment`;
    public readonly addressDividerAddressLanguageItemName: string = `AddressDivider.Address`;
    public readonly virtualAddressDividerStreetLanguageItemName: string = `VirtualAddressDivider.Street`;
    public readonly virtualAddressDividerCityLanguageItemName: string = `VirtualAddressDivider.City`;
    public readonly virtualAddressDividerPostalcodeLanguageItemName: string = `VirtualAddressDivider.Postalcode`;
    public readonly fileInputDragAndDropLanguageItemName: string = `FileInput.DragAndDrop`;
    public readonly fileInputReadonlyLanguageItemName: string = `FileInput.Readonly`;
    public readonly documentPreviewModalPreviewLanguageItemName: string = `DocumentPreviewModal.Preview`;
    public readonly fileInputChooseFileLanguageItemName: string = `FileInput.ChooseFile`;
    public readonly alertLanguageItemName: string = `Alert`;
    public readonly textInputLanguageItemName: string = `TextInput`;
    public readonly topNavLanguageItemName: string = `TopNav`;
    public readonly footerLanguageItemName: string = `Footer`;
    public readonly iconLanguageItemName: string = `Icon`;
    public readonly dropdownWidgetLanguageItemName: string = `DropdownWidget`;
    public readonly widgetContainerLanguageItemName: string = `WidgetContainer`;
    public readonly locationPickerModalTitleLanguageItemName: string = `LocationPickerModal.Title`;
    public readonly locationPickerModalSubtitleLanguageItemName: string = `LocationPickerModal.Subtitle`;
    public readonly locationPickerModalSetLocationLanguageItemName: string = `LocationPickerModal.SetLocation`;
    public readonly dropdownNoItemsLanguageItemName: string = `Dropdown.NoItems`;
    public readonly dropdownNoDataLanguageItemName: string = `Dropdown.NoData`;
    public readonly dropdownFilterResultsLanguageItemName: string = `Dropdown.FilterResults`;
    public readonly dropdownGetResultsLanguageItemName: string = `Dropdown.GetResults`;
    public readonly dropdownAddLanguageItemName: string = `Dropdown.Add`;
    public readonly dropdownNothingSelectedLanguageItemName: string = `Dropdown.NothingSelected`;
    public readonly passwordInputHelpTextLengthLanguageItemName: string = `PasswordInput.HelpText.Length`;
    public readonly documentPreviewModalDownloadLanguageItemName: string = `DocumentPreviewModal.Download`;
    public readonly fileInputPreviewLanguageItemName: string = `FileInput.Preview`;
    public readonly gridLanguageItemName: string = `Grid`;
    public readonly addressInputLanguageItemName: string = `AddressInput`;
    public readonly buttonContainerLanguageItemName: string = `ButtonContainer`;
    public readonly checkboxLanguageItemName: string = `Checkbox`;
    public readonly checkboxNullableLanguageItemName: string = `CheckboxNullable`;
    public readonly documentPreviewLanguageItemName: string = `DocumentPreview`;
    public readonly emailInputLanguageItemName: string = `EmailInput`;
    public readonly layoutFourColumnsLanguageItemName: string = `Layout.FourColumns`;
    public readonly linkLanguageItemName: string = `Link`;
    public readonly locationPickerLanguageItemName: string = `LocationPicker`;
    public readonly numberInputLanguageItemName: string = `NumberInput`;
    public readonly layoutOneColumnLanguageItemName: string = `Layout.OneColumn`;
    public readonly layoutInlineLanguageItemName: string = `Layout.Inline`;
    public readonly paginationLanguageItemName: string = `Pagination`;
    public readonly phoneInputLanguageItemName: string = `PhoneInput`;
    public readonly popoverLanguageItemName: string = `Popover`;
    public readonly sliderLanguageItemName: string = `Slider`;
    public readonly spinnerLanguageItemName: string = `Spinner`;
    public readonly switchLanguageItemName: string = `Switch`;
    public readonly switchNullableLanguageItemName: string = `SwitchNullable`;
    public readonly tabContainerLanguageItemName: string = `TabContainer`;
    public readonly textAreaInputLanguageItemName: string = `TextAreaInput`;
    public readonly layoutThreeColumnsLanguageItemName: string = `Layout.ThreeColumns`;
    public readonly layoutTwoColumnsLanguageItemName: string = `Layout.TwoColumns`;
    public readonly checkboxWidgetLanguageItemName: string = `CheckboxWidget`;
    public readonly checkStepWidgetLanguageItemName: string = `CheckStepWidget`;
    public readonly dateInputWidgetLanguageItemName: string = `DateInputWidget`;
    public readonly linkWidgetLanguageItemName: string = `LinkWidget`;
    public readonly routeWidgetLanguageItemName: string = `RouteWidget`;
    public readonly timeWidgetLanguageItemName: string = `TimeWidget`;
    public readonly numberWidgetLanguageItemName: string = `NumberWidget`;
    public readonly qrWidgetScanErrorLanguageItemName: string = `QrWidget.Scan.Error`;
    public readonly switchWidgetLanguageItemName: string = `SwitchWidget`;
    public readonly textAreaWidgetLanguageItemName: string = `TextAreaWidget`;
    public readonly textInputWidgetLanguageItemName: string = `TextInputWidget`;
    public readonly stepsWidgetLanguageItemName: string = `StepsWidget`;
    public readonly titleWidgetLanguageItemName: string = `TitleWidget`;
    public readonly buttonLanguageItemName: string = `Button`;
    public readonly dateInputLanguageItemName: string = `DateInput`;
    public readonly formLanguageItemName: string = `Form`;
    public readonly layoutLanguageItemName: string = `Layout`;
    public readonly wizardContainerLanguageItemName: string = `WizardContainer`;
    public readonly baseInputValidatorsRequiredLanguageItemName: string = `BaseInput.Validators.Required`;
    public readonly baseInputValidatorsLengthLanguageItemName: string = `BaseInput.Validators.Length`;
    public readonly baseInputValidatorsNumberRangeLanguageItemName: string = `BaseInput.Validators.NumberRange`;
    public readonly baseInputValidatorsDocumentTypeNotSupportedLanguageItemName: string = `BaseInput.Validators.DocumentTypeNotSupported`;
    public readonly baseInputValidatorsDocumentTooBigLanguageItemName: string = `BaseInput.Validators.DocumentTooBig`;
    public readonly baseInputValidatorsTotalSizeTooBigLanguageItemName: string = `BaseInput.Validators.TotalSizeTooBig`;
    public readonly monthJanuaryLanguageItemName: string = `Month.January`;
    public readonly monthFebruaryLanguageItemName: string = `Month.February`;
    public readonly monthMarchLanguageItemName: string = `Month.March`;
    public readonly monthAprilLanguageItemName: string = `Month.April`;
    public readonly monthMayLanguageItemName: string = `Month.May`;
    public readonly monthJuneLanguageItemName: string = `Month.June`;
    public readonly monthJulyLanguageItemName: string = `Month.July`;
    public readonly monthAugustLanguageItemName: string = `Month.August`;
    public readonly monthSeptemberLanguageItemName: string = `Month.September`;
    public readonly monthOctoberLanguageItemName: string = `Month.October`;
    public readonly monthNovemberLanguageItemName: string = `Month.November`;
    public readonly monthDecemberLanguageItemName: string = `Month.December`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "da", label: "Dansk" },
                { code: "fi", label: "Suomi" },
                { code: "nb", label: "Norsk bokmål" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська" }
            ],
            "en");
        
        //Initializer
        this.set(this.dropdownMultipleSelectedLanguageItemName, { language: `en`, value: `{0} selected` }, { language: `uk`, value: `{0} вибран(о)` }, { language: `sv`, value: `{0} valt` }, { language: `ru`, value: `{0} выбран(о)` }, { language: `pl`, value: `PL: {0} selected` }, { language: `nb`, value: `{0} selected` }, { language: `fi`, value: `{0} valittu` }, { language: `da`, value: `{0} selected` },);
        this.set(this.listLoadingLanguageItemName, { language: `en`, value: `Loading...` }, { language: `uk`, value: `Завантаження...` }, { language: `sv`, value: `Laddar...` }, { language: `ru`, value: `Загрузка...` }, { language: `pl`, value: `PL: Loading...` }, { language: `nb`, value: `Loading...` }, { language: `fi`, value: `Ladataan...` }, { language: `da`, value: `Loading...` },);
        this.set(this.signatureWidgetClearLanguageItemName, { language: `en`, value: `Clear` }, { language: `uk`, value: `Очистити` }, { language: `sv`, value: `Töm` }, { language: `ru`, value: `Очистить` }, { language: `pl`, value: `PL: Clear` }, { language: `nb`, value: `Clear` }, { language: `fi`, value: `Tyhjennä` }, { language: `da`, value: `Clear` },);
        this.set(this.signatureWidgetDoneLanguageItemName, { language: `en`, value: `Done` }, { language: `uk`, value: `Завершити` }, { language: `sv`, value: `Färdig` }, { language: `ru`, value: `Завершить` }, { language: `pl`, value: `PL: Done` }, { language: `nb`, value: `Done` }, { language: `fi`, value: `Valmis` }, { language: `da`, value: `Done` },);
        this.set(this.modalSaveChangesLanguageItemName, { language: `en`, value: `Save changes` }, { language: `uk`, value: `Зберегти зміни` }, { language: `sv`, value: `Spara ändringar` }, { language: `ru`, value: `Сохранить изменения` }, { language: `pl`, value: `PL: Save changes` }, { language: `nb`, value: `Save changes` }, { language: `fi`, value: `Tallenna muutokset` }, { language: `da`, value: `Save changes` },);
        this.set(this.modalCloseLanguageItemName, { language: `en`, value: `Close` }, { language: `uk`, value: `Закрити` }, { language: `sv`, value: `Stäng` }, { language: `ru`, value: `Закрыть` }, { language: `pl`, value: `PL: Close` }, { language: `nb`, value: `Close` }, { language: `fi`, value: `Sulje` }, { language: `da`, value: `Close` },);
        this.set(this.pageContainerPageHelpLanguageItemName, { language: `en`, value: `Page help` }, { language: `uk`, value: `Довідка` }, { language: `sv`, value: `Sidhjälp` }, { language: `ru`, value: `Справка` }, { language: `pl`, value: `PL: Page help` }, { language: `nb`, value: `Page help` }, { language: `fi`, value: `Sivun ohje` }, { language: `da`, value: `Page help` },);
        this.set(this.navigationWidgetPreviousLanguageItemName, { language: `en`, value: `Previous` }, { language: `uk`, value: `Назад` }, { language: `sv`, value: `Föregående` }, { language: `ru`, value: `RU: Previous` }, { language: `pl`, value: `PL: Previous` }, { language: `nb`, value: `Previous` }, { language: `fi`, value: `Edellinen` }, { language: `da`, value: `Previous` },);
        this.set(this.navigationWidgetReturnToPreviousLanguageItemName, { language: `en`, value: `Return to previous step` }, { language: `uk`, value: `Повернутися до попереднього кроку` }, { language: `sv`, value: `Återgå till föregående steg` }, { language: `ru`, value: `RU: Return to previous step` }, { language: `pl`, value: `PL: Return to previous step` }, { language: `nb`, value: `Return to previous step` }, { language: `fi`, value: `Palaa edelliseen vaiheeseen` }, { language: `da`, value: `Return to previous step` },);
        this.set(this.navigationWidgetNextLanguageItemName, { language: `en`, value: `Next` }, { language: `uk`, value: `Далі` }, { language: `sv`, value: `Nästa` }, { language: `ru`, value: `RU: Next` }, { language: `pl`, value: `PL: Next` }, { language: `nb`, value: `Next` }, { language: `fi`, value: `Seuraava` }, { language: `da`, value: `Next` },);
        this.set(this.navigationWidgetGoToNextLanguageItemName, { language: `en`, value: `Go to next step` }, { language: `uk`, value: `Перейти до наступного кроку` }, { language: `sv`, value: `Gå till nästa steg` }, { language: `ru`, value: `RU: Go to next step` }, { language: `pl`, value: `PL: Go to next step` }, { language: `nb`, value: `Go to next step` }, { language: `fi`, value: `Siirry seuraavaan vaiheeseen` }, { language: `da`, value: `Go to next step` },);
        this.set(this.confirmationDialogAreYouSureLanguageItemName, { language: `en`, value: `Are you sure?` }, { language: `uk`, value: `Ви впевнені?` }, { language: `sv`, value: `Är du säker?` }, { language: `ru`, value: `Вы уверены?` }, { language: `pl`, value: `PL: Are you sure?` }, { language: `nb`, value: `Are you sure?` }, { language: `fi`, value: `Oletko varma?` }, { language: `da`, value: `Are you sure?` },);
        this.set(this.confirmationDialogConfirmButtonLanguageItemName, { language: `en`, value: `Confirm` }, { language: `uk`, value: `Підтвердети` }, { language: `sv`, value: `Bekräfta` }, { language: `ru`, value: `Подтвердить` }, { language: `pl`, value: `PL: Confirm` }, { language: `nb`, value: `Confirm` }, { language: `fi`, value: `Kyllä` }, { language: `da`, value: `Confirm` },);
        this.set(this.confirmationDialogCloseButtonLanguageItemName, { language: `en`, value: `Close` }, { language: `uk`, value: `Закрити` }, { language: `sv`, value: `SV: Close` }, { language: `ru`, value: `Отмена` }, { language: `pl`, value: `PL: Close` }, { language: `nb`, value: `Close` }, { language: `fi`, value: `Ei` }, { language: `da`, value: `Close` },);
        this.set(this.confirmationDialogCommentLanguageItemName, { language: `en`, value: `Please leave a comment` }, { language: `uk`, value: `Будьласка, залиште коментар` }, { language: `sv`, value: `Var vänlig och lämna en kommentar` }, { language: `ru`, value: `Пожалуйста, оставьте комментарий` }, { language: `pl`, value: `PL: Please leave a comment` }, { language: `nb`, value: `Please leave a comment` }, { language: `fi`, value: `Ole hyvä ja kommentoi` }, { language: `da`, value: `Please leave a comment` },);
        this.set(this.addressDividerAddressLanguageItemName, { language: `en`, value: `Address` }, { language: `uk`, value: `Адреса` }, { language: `sv`, value: `Adress` }, { language: `ru`, value: `Адрес` }, { language: `pl`, value: `PL: Address` }, { language: `nb`, value: `Address` }, { language: `fi`, value: `Osoite` }, { language: `da`, value: `Address` },);
        this.set(this.virtualAddressDividerStreetLanguageItemName, { language: `en`, value: `Street` }, { language: `uk`, value: `Вулиця` }, { language: `sv`, value: `Gata` }, { language: `ru`, value: `RU: Street` }, { language: `pl`, value: `PL: Street` }, { language: `nb`, value: `Street` }, { language: `fi`, value: `Katu` }, { language: `da`, value: `Street` },);
        this.set(this.virtualAddressDividerCityLanguageItemName, { language: `en`, value: `City` }, { language: `uk`, value: `Місто` }, { language: `sv`, value: `Stad` }, { language: `ru`, value: `RU: City` }, { language: `pl`, value: `PL: City` }, { language: `nb`, value: `City` }, { language: `fi`, value: `Kaupunki` }, { language: `da`, value: `City` },);
        this.set(this.virtualAddressDividerPostalcodeLanguageItemName, { language: `en`, value: `Postal code` }, { language: `uk`, value: `Поштовий індекс` }, { language: `sv`, value: `Postnummer` }, { language: `ru`, value: `RU: Postal code` }, { language: `pl`, value: `PL: Postal code` }, { language: `nb`, value: `Postal code` }, { language: `fi`, value: `Postinumero` }, { language: `da`, value: `Postal code` },);
        this.set(this.fileInputDragAndDropLanguageItemName, { language: `en`, value: `Drag'n'drop file here, or click to select` }, { language: `uk`, value: `Перетягніть файл, або оберіть його` }, { language: `sv`, value: `dra och släpp filen här, eller välj med att klicka` }, { language: `ru`, value: `RU: Drag'n'drop file here, or click to select` }, { language: `pl`, value: `PL: Drag'n'drop file here, or click to select` }, { language: `nb`, value: `Drag'n'drop file here, or click to select` }, { language: `fi`, value: `Pudota tiedosto tähän tai valitse klikkaamalla` }, { language: `da`, value: `Drag'n'drop file here, or click to select` },);
        this.set(this.fileInputReadonlyLanguageItemName, { language: `en`, value: `File is readonly` }, { language: `uk`, value: `UK: File is readonly` }, { language: `sv`, value: `Filen är bara läsbar` }, { language: `ru`, value: `RU: File is readonly` }, { language: `pl`, value: `PL: File is readonly` }, { language: `nb`, value: `File is readonly` }, { language: `fi`, value: `Tämä tiedosto on vain luettavissa` }, { language: `da`, value: `File is readonly` },);
        this.set(this.documentPreviewModalPreviewLanguageItemName, { language: `en`, value: `Preview` }, { language: `uk`, value: `Переглянути` }, { language: `sv`, value: `Förhandsvisning` }, { language: `ru`, value: `RU: Preview` }, { language: `pl`, value: `PL: Preview` }, { language: `nb`, value: `Preview` }, { language: `fi`, value: `Esikatselu` }, { language: `da`, value: `Preview` },);
        this.set(this.fileInputChooseFileLanguageItemName, { language: `en`, value: `Choose file` }, { language: `uk`, value: `Оберіть файл` }, { language: `sv`, value: `Välj fil` }, { language: `ru`, value: `RU: Choose file` }, { language: `pl`, value: `PL: Choose file` }, { language: `nb`, value: `Choose file` }, { language: `fi`, value: `Valitse tiedosto` }, { language: `da`, value: `Choose file` },);
        this.set(this.alertLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `sv`, value: `` }, { language: `ru`, value: `` }, { language: `pl`, value: `` }, { language: `nb`, value: `` }, { language: `fi`, value: `` }, { language: `da`, value: `` },);
        this.set(this.textInputLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `sv`, value: `` }, { language: `ru`, value: `` }, { language: `pl`, value: `` }, { language: `nb`, value: `` }, { language: `fi`, value: `` }, { language: `da`, value: `` },);
        this.set(this.topNavLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `sv`, value: `` }, { language: `ru`, value: `` }, { language: `pl`, value: `` }, { language: `nb`, value: `` }, { language: `fi`, value: `` }, { language: `da`, value: `` },);
        this.set(this.footerLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `sv`, value: `` }, { language: `ru`, value: `` }, { language: `pl`, value: `` }, { language: `nb`, value: `` }, { language: `fi`, value: `` }, { language: `da`, value: `` },);
        this.set(this.iconLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `sv`, value: `` }, { language: `ru`, value: `` }, { language: `pl`, value: `` }, { language: `nb`, value: `` }, { language: `fi`, value: `` }, { language: `da`, value: `` },);
        this.set(this.dropdownWidgetLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `sv`, value: `` }, { language: `ru`, value: `` }, { language: `pl`, value: `` }, { language: `nb`, value: `` }, { language: `fi`, value: `` }, { language: `da`, value: `` },);
        this.set(this.widgetContainerLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.locationPickerModalTitleLanguageItemName, { language: `en`, value: `Location picker` }, { language: `uk`, value: `UK: Location picker` }, { language: `sv`, value: `Platsväljare` }, { language: `ru`, value: `RU: Location picker` }, { language: `pl`, value: `PL: Location picker` }, { language: `nb`, value: `Location picker` }, { language: `fi`, value: `Sijaintivalitsin` }, { language: `da`, value: `Location picker` },);
        this.set(this.locationPickerModalSubtitleLanguageItemName, { language: `en`, value: `Choose location on map` }, { language: `uk`, value: `Оберіть місце на мапі` }, { language: `sv`, value: `Välj plats på kartan` }, { language: `ru`, value: `RU: Choose location on map` }, { language: `pl`, value: `PL: Choose location on map` }, { language: `nb`, value: `Choose location on map` }, { language: `fi`, value: `Valitse sijainti kartalla` }, { language: `da`, value: `Choose location on map` },);
        this.set(this.locationPickerModalSetLocationLanguageItemName, { language: `en`, value: `Set location` }, { language: `uk`, value: `Оберіть адресу` }, { language: `sv`, value: `SV: Set location` }, { language: `ru`, value: `RU: Set location` }, { language: `pl`, value: `Ställ in plats` }, { language: `nb`, value: `Set location` }, { language: `fi`, value: `Aseta sijainti` }, { language: `da`, value: `Set location` },);
        this.set(this.dropdownNoItemsLanguageItemName, { language: `en`, value: `No items found` }, { language: `uk`, value: `Нічого не знайдено` }, { language: `sv`, value: `Inga objekt hittades` }, { language: `ru`, value: `Данные не найдены` }, { language: `pl`, value: `PL: No items found` }, { language: `nb`, value: `No items found` }, { language: `fi`, value: `Kohteita ei löytynyt` }, { language: `da`, value: `No items found` },);
        this.set(this.dropdownNoDataLanguageItemName, { language: `en`, value: `No data` }, { language: `uk`, value: `Немає даних` }, { language: `sv`, value: `Ingen information` }, { language: `ru`, value: `Нет данных` }, { language: `pl`, value: `PL: No data` }, { language: `nb`, value: `No data` }, { language: `fi`, value: `Ei tietoja` }, { language: `da`, value: `No data` },);
        this.set(this.dropdownFilterResultsLanguageItemName, { language: `en`, value: `Filter results` }, { language: `uk`, value: `UK: Filter results` }, { language: `sv`, value: `Filtrera resultat` }, { language: `ru`, value: `RU: Filter results` }, { language: `pl`, value: `PL: Filter results` }, { language: `nb`, value: `Filter results` }, { language: `fi`, value: `Suodata tulokset` }, { language: `da`, value: `Filter results` },);
        this.set(this.dropdownGetResultsLanguageItemName, { language: `en`, value: `Start typing to get results` }, { language: `uk`, value: `Почніть писати, щоб побачити дані` }, { language: `sv`, value: `Börja skriva för att få resultat` }, { language: `ru`, value: `Начните писать, чтобы увидеть данные` }, { language: `pl`, value: `PL: Start typing to get results` }, { language: `nb`, value: `Start typing to get results` }, { language: `fi`, value: `Aloita kirjoittaminen saadaksesi tuloksia` }, { language: `da`, value: `Start typing to get results` },);
        this.set(this.dropdownAddLanguageItemName, { language: `en`, value: `Add` }, { language: `uk`, value: `Додати` }, { language: `sv`, value: `SV: Add` }, { language: `ru`, value: `Новый` }, { language: `pl`, value: `PL: Add` }, { language: `nb`, value: `Add` }, { language: `fi`, value: `Lisää` }, { language: `da`, value: `Add` },);
        this.set(this.dropdownNothingSelectedLanguageItemName, { language: `en`, value: `Nothing is selected` }, { language: `uk`, value: `Нічого не вибрано` }, { language: `sv`, value: `Ingenting är valt` }, { language: `ru`, value: `Ничего не выбрано` }, { language: `pl`, value: `PL: Nothing is selected` }, { language: `nb`, value: `Nothing is selected` }, { language: `fi`, value: `Ei mitään valittu` }, { language: `da`, value: `Nothing is selected` },);
        this.set(this.passwordInputHelpTextLengthLanguageItemName, { language: `en`, value: `at least 8 characters long` }, { language: `uk`, value: `Не менше 8 символів` }, { language: `sv`, value: `åtminstone 8 tecken` }, { language: `ru`, value: `RU: at least 8 characters long` }, { language: `pl`, value: `PL: at least 8 characters long` }, { language: `nb`, value: `at least 8 characters long` }, { language: `fi`, value: `vähintään 8 merkkiä` }, { language: `da`, value: `at least 8 characters long` },);
        this.set(this.documentPreviewModalDownloadLanguageItemName, { language: `en`, value: `Download` }, { language: `uk`, value: `Завантажити` }, { language: `sv`, value: `SV: Download` }, { language: `ru`, value: `Загрузить` }, { language: `pl`, value: `PL: Download` }, { language: `nb`, value: `Download` }, { language: `fi`, value: `FI: Download` }, { language: `da`, value: `Download` },);
        this.set(this.fileInputPreviewLanguageItemName, { language: `en`, value: `Preview` }, { language: `uk`, value: `Переглянути` }, { language: `sv`, value: `Förhandsvisning` }, { language: `ru`, value: `RU: Preview` }, { language: `pl`, value: `PL: Preview` }, { language: `nb`, value: `Preview` }, { language: `fi`, value: `Esikatselu` }, { language: `da`, value: `Preview` },);
        this.set(this.gridLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.addressInputLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.buttonContainerLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.checkboxLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.checkboxNullableLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.documentPreviewLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.emailInputLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.layoutFourColumnsLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.linkLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.locationPickerLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.numberInputLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.layoutOneColumnLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.layoutInlineLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.paginationLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.phoneInputLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.popoverLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.sliderLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.spinnerLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.switchLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.switchNullableLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.tabContainerLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.textAreaInputLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.layoutThreeColumnsLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.layoutTwoColumnsLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.checkboxWidgetLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.checkStepWidgetLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.dateInputWidgetLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.linkWidgetLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.routeWidgetLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.timeWidgetLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.numberWidgetLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.qrWidgetScanErrorLanguageItemName, { language: `en`, value: `QR code scanner is not available, probably no permissions to camera on your mobile device.` }, { language: `uk`, value: `QR код сканер не доступний, можливо немає дозволу на використання камери вашого девайсу.` }, { language: `sv`, value: `QR-kodskanner inte tillgänglig, förmodligen inga behörigheter för kameran på din mobila enhet.` }, { language: `ru`, value: `RU: QR code scanner not available, probably no permissions to camera on you mobile device.` }, { language: `pl`, value: `PL: QR code scanner not available, probably no permissions to camera on you mobile device.` }, { language: `nb`, value: `QR code scanner is not available, probably no permissions to camera on your mobile device.` }, { language: `fi`, value: `QR koodi skanneri ei käytössä. Mahdollisesti kameran käyttöoikeudet puuttuvat laitteeltasi.` }, { language: `da`, value: `QR code scanner is not available, probably no permissions to camera on your mobile device.` },);
        this.set(this.switchWidgetLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.textAreaWidgetLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.textInputWidgetLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.stepsWidgetLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.titleWidgetLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.buttonLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.dateInputLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.formLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.layoutLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.wizardContainerLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` }, { language: `nb`, value: `` }, { language: `da`, value: `` },);
        this.set(this.baseInputValidatorsRequiredLanguageItemName, { language: `en`, value: `{0} is required` }, { language: `sv`, value: `{0} krävs` }, { language: `nb`, value: `{0} er påkrevd` }, { language: `fi`, value: `{0} on pakollinen` },);
        this.set(this.baseInputValidatorsLengthLanguageItemName, { language: `en`, value: `Text is too short` }, { language: `sv`, value: `Text för kort` }, { language: `nb`, value: `Teksten er for kort` }, { language: `fi`, value: `Teksti on liian lyhyt` },);
        this.set(this.baseInputValidatorsNumberRangeLanguageItemName, { language: `en`, value: `Value must be in range {0} - {1}` }, { language: `fi`, value: `Arvo pitää olla välistä {0} - {1}` },);
        this.set(this.baseInputValidatorsDocumentTypeNotSupportedLanguageItemName, { language: `en`, value: `Document type is not supported, choose file with extension {0}` }, { language: `sv`, value: `Dokumenttyp stöds inte. Välj dokument som är {0}.` }, { language: `fi`, value: `Dokumentin tyyppi ei ole tuettu. Valitse tiedosto, joka on {0}` },);
        this.set(this.baseInputValidatorsDocumentTooBigLanguageItemName, { language: `en`, value: `Document file is too big` }, { language: `sv`, value: `Dokument filen är för stor` }, { language: `fi`, value: `Dokumentti tiedosto liian iso` },);
        this.set(this.baseInputValidatorsTotalSizeTooBigLanguageItemName, { language: `en`, value: `Total size of documents is too big` }, { language: `fi`, value: `Dokumenttien kokonaiskoko on liian iso` },);
        this.set(this.monthJanuaryLanguageItemName, { language: `en`, value: `January` }, { language: `ru`, value: `Январь` }, { language: `fi`, value: `Helmikuu` },);
        this.set(this.monthFebruaryLanguageItemName, { language: `en`, value: `February` }, { language: `ru`, value: `Февраль` }, { language: `fi`, value: `Tammikuu` },);
        this.set(this.monthMarchLanguageItemName, { language: `en`, value: `March` }, { language: `ru`, value: `Март` }, { language: `fi`, value: `Maaliskuu` },);
        this.set(this.monthAprilLanguageItemName, { language: `en`, value: `April` }, { language: `ru`, value: `Апрель` }, { language: `fi`, value: `Huhtikuu` },);
        this.set(this.monthMayLanguageItemName, { language: `en`, value: `May` }, { language: `ru`, value: `Май` }, { language: `fi`, value: `Toukokuu` },);
        this.set(this.monthJuneLanguageItemName, { language: `en`, value: `June` }, { language: `ru`, value: `Июнь` }, { language: `fi`, value: `Kesäkuu` },);
        this.set(this.monthJulyLanguageItemName, { language: `en`, value: `July` }, { language: `ru`, value: `Июль` }, { language: `fi`, value: `Heinäkuu` },);
        this.set(this.monthAugustLanguageItemName, { language: `en`, value: `August` }, { language: `ru`, value: `Август` }, { language: `fi`, value: `Elokuu` },);
        this.set(this.monthSeptemberLanguageItemName, { language: `en`, value: `September` }, { language: `ru`, value: `Декабрь` }, { language: `fi`, value: `Syyskuu` },);
        this.set(this.monthOctoberLanguageItemName, { language: `en`, value: `October` }, { language: `ru`, value: `Октябрь` }, { language: `fi`, value: `Lokakuu` },);
        this.set(this.monthNovemberLanguageItemName, { language: `en`, value: `November` }, { language: `ru`, value: `Ноябрь` }, { language: `fi`, value: `Marraskuu` },);
        this.set(this.monthDecemberLanguageItemName, { language: `en`, value: `December` }, { language: `ru`, value: `Декабрь` }, { language: `fi`, value: `Joulukuu` },);
    }

    /**
    /* "Dropdown.MultipleSelected" ({0} selected)
    */
    public get dropdownMultipleSelected() : string {
        return this.get(this.dropdownMultipleSelectedLanguageItemName);
    }

    /**
    /* "List.Loading" (Loading...)
    */
    public get listLoading() : string {
        return this.get(this.listLoadingLanguageItemName);
    }

    /**
    /* "SignatureWidget.Clear" (Clear)
    */
    public get signatureWidgetClear() : string {
        return this.get(this.signatureWidgetClearLanguageItemName);
    }

    /**
    /* "SignatureWidget.Done" (Done)
    */
    public get signatureWidgetDone() : string {
        return this.get(this.signatureWidgetDoneLanguageItemName);
    }

    /**
    /* "Modal.SaveChanges" (Save changes)
    */
    public get modalSaveChanges() : string {
        return this.get(this.modalSaveChangesLanguageItemName);
    }

    /**
    /* "Modal.Close" (Close)
    */
    public get modalClose() : string {
        return this.get(this.modalCloseLanguageItemName);
    }

    /**
    /* "PageContainer.PageHelp" (Page help)
    */
    public get pageContainerPageHelp() : string {
        return this.get(this.pageContainerPageHelpLanguageItemName);
    }

    /**
    /* "NavigationWidget.Previous" (Previous)
    */
    public get navigationWidgetPrevious() : string {
        return this.get(this.navigationWidgetPreviousLanguageItemName);
    }

    /**
    /* "NavigationWidget.ReturnToPrevious" (Return to previous step)
    */
    public get navigationWidgetReturnToPrevious() : string {
        return this.get(this.navigationWidgetReturnToPreviousLanguageItemName);
    }

    /**
    /* "NavigationWidget.Next" (Next)
    */
    public get navigationWidgetNext() : string {
        return this.get(this.navigationWidgetNextLanguageItemName);
    }

    /**
    /* "NavigationWidget.GoToNext" (Go to next step)
    */
    public get navigationWidgetGoToNext() : string {
        return this.get(this.navigationWidgetGoToNextLanguageItemName);
    }

    /**
    /* "ConfirmationDialog.AreYouSure" (Are you sure?)
    */
    public get confirmationDialogAreYouSure() : string {
        return this.get(this.confirmationDialogAreYouSureLanguageItemName);
    }

    /**
    /* "ConfirmationDialog.ConfirmButton" (Confirm)
    */
    public get confirmationDialogConfirmButton() : string {
        return this.get(this.confirmationDialogConfirmButtonLanguageItemName);
    }

    /**
    /* "ConfirmationDialog.CloseButton" (Close)
    */
    public get confirmationDialogCloseButton() : string {
        return this.get(this.confirmationDialogCloseButtonLanguageItemName);
    }

    /**
    /* "ConfirmationDialog.Comment" (Please leave a comment)
    */
    public get confirmationDialogComment() : string {
        return this.get(this.confirmationDialogCommentLanguageItemName);
    }

    /**
    /* "AddressDivider.Address" (Address)
    */
    public get addressDividerAddress() : string {
        return this.get(this.addressDividerAddressLanguageItemName);
    }

    /**
    /* "VirtualAddressDivider.Street" (Street)
    */
    public get virtualAddressDividerStreet() : string {
        return this.get(this.virtualAddressDividerStreetLanguageItemName);
    }

    /**
    /* "VirtualAddressDivider.City" (City)
    */
    public get virtualAddressDividerCity() : string {
        return this.get(this.virtualAddressDividerCityLanguageItemName);
    }

    /**
    /* "VirtualAddressDivider.Postalcode" (Postal code)
    */
    public get virtualAddressDividerPostalcode() : string {
        return this.get(this.virtualAddressDividerPostalcodeLanguageItemName);
    }

    /**
    /* "FileInput.DragAndDrop" (Drag'n'drop file here, or click to select)
    */
    public get fileInputDragAndDrop() : string {
        return this.get(this.fileInputDragAndDropLanguageItemName);
    }

    /**
    /* "FileInput.Readonly" (File is readonly)
    */
    public get fileInputReadonly() : string {
        return this.get(this.fileInputReadonlyLanguageItemName);
    }

    /**
    /* "DocumentPreviewModal.Preview" (Preview)
    */
    public get documentPreviewModalPreview() : string {
        return this.get(this.documentPreviewModalPreviewLanguageItemName);
    }

    /**
    /* "FileInput.ChooseFile" (Choose file)
    */
    public get fileInputChooseFile() : string {
        return this.get(this.fileInputChooseFileLanguageItemName);
    }

    /**
    /* "Alert" ()
    */
    public get alert() : string {
        return this.get(this.alertLanguageItemName);
    }

    /**
    /* "TextInput" ()
    */
    public get textInput() : string {
        return this.get(this.textInputLanguageItemName);
    }

    /**
    /* "TopNav" ()
    */
    public get topNav() : string {
        return this.get(this.topNavLanguageItemName);
    }

    /**
    /* "Footer" ()
    */
    public get footer() : string {
        return this.get(this.footerLanguageItemName);
    }

    /**
    /* "Icon" ()
    */
    public get icon() : string {
        return this.get(this.iconLanguageItemName);
    }

    /**
    /* "DropdownWidget" ()
    */
    public get dropdownWidget() : string {
        return this.get(this.dropdownWidgetLanguageItemName);
    }

    /**
    /* "WidgetContainer" ()
    */
    public get widgetContainer() : string {
        return this.get(this.widgetContainerLanguageItemName);
    }

    /**
    /* "LocationPickerModal.Title" (Location picker)
    */
    public get locationPickerModalTitle() : string {
        return this.get(this.locationPickerModalTitleLanguageItemName);
    }

    /**
    /* "LocationPickerModal.Subtitle" (Choose location on map)
    */
    public get locationPickerModalSubtitle() : string {
        return this.get(this.locationPickerModalSubtitleLanguageItemName);
    }

    /**
    /* "LocationPickerModal.SetLocation" (Set location)
    */
    public get locationPickerModalSetLocation() : string {
        return this.get(this.locationPickerModalSetLocationLanguageItemName);
    }

    /**
    /* "Dropdown.NoItems" (No items found)
    */
    public get dropdownNoItems() : string {
        return this.get(this.dropdownNoItemsLanguageItemName);
    }

    /**
    /* "Dropdown.NoData" (No data)
    */
    public get dropdownNoData() : string {
        return this.get(this.dropdownNoDataLanguageItemName);
    }

    /**
    /* "Dropdown.FilterResults" (Filter results)
    */
    public get dropdownFilterResults() : string {
        return this.get(this.dropdownFilterResultsLanguageItemName);
    }

    /**
    /* "Dropdown.GetResults" (Start typing to get results)
    */
    public get dropdownGetResults() : string {
        return this.get(this.dropdownGetResultsLanguageItemName);
    }

    /**
    /* "Dropdown.Add" (Add)
    */
    public get dropdownAdd() : string {
        return this.get(this.dropdownAddLanguageItemName);
    }

    /**
    /* "Dropdown.NothingSelected" (Nothing is selected)
    */
    public get dropdownNothingSelected() : string {
        return this.get(this.dropdownNothingSelectedLanguageItemName);
    }

    /**
    /* "PasswordInput.HelpText.Length" (at least 8 characters long)
    */
    public get passwordInputHelpTextLength() : string {
        return this.get(this.passwordInputHelpTextLengthLanguageItemName);
    }

    /**
    /* "DocumentPreviewModal.Download" (Download)
    */
    public get documentPreviewModalDownload() : string {
        return this.get(this.documentPreviewModalDownloadLanguageItemName);
    }

    /**
    /* "FileInput.Preview" (Preview)
    */
    public get fileInputPreview() : string {
        return this.get(this.fileInputPreviewLanguageItemName);
    }

    /**
    /* "Grid" ()
    */
    public get grid() : string {
        return this.get(this.gridLanguageItemName);
    }

    /**
    /* "AddressInput" ()
    */
    public get addressInput() : string {
        return this.get(this.addressInputLanguageItemName);
    }

    /**
    /* "ButtonContainer" ()
    */
    public get buttonContainer() : string {
        return this.get(this.buttonContainerLanguageItemName);
    }

    /**
    /* "Checkbox" ()
    */
    public get checkbox() : string {
        return this.get(this.checkboxLanguageItemName);
    }

    /**
    /* "CheckboxNullable" ()
    */
    public get checkboxNullable() : string {
        return this.get(this.checkboxNullableLanguageItemName);
    }

    /**
    /* "DocumentPreview" ()
    */
    public get documentPreview() : string {
        return this.get(this.documentPreviewLanguageItemName);
    }

    /**
    /* "EmailInput" ()
    */
    public get emailInput() : string {
        return this.get(this.emailInputLanguageItemName);
    }

    /**
    /* "Layout.FourColumns" ()
    */
    public get layoutFourColumns() : string {
        return this.get(this.layoutFourColumnsLanguageItemName);
    }

    /**
    /* "Link" ()
    */
    public get link() : string {
        return this.get(this.linkLanguageItemName);
    }

    /**
    /* "LocationPicker" ()
    */
    public get locationPicker() : string {
        return this.get(this.locationPickerLanguageItemName);
    }

    /**
    /* "NumberInput" ()
    */
    public get numberInput() : string {
        return this.get(this.numberInputLanguageItemName);
    }

    /**
    /* "Layout.OneColumn" ()
    */
    public get layoutOneColumn() : string {
        return this.get(this.layoutOneColumnLanguageItemName);
    }

    /**
    /* "Layout.Inline" ()
    */
    public get layoutInline() : string {
        return this.get(this.layoutInlineLanguageItemName);
    }

    /**
    /* "Pagination" ()
    */
    public get pagination() : string {
        return this.get(this.paginationLanguageItemName);
    }

    /**
    /* "PhoneInput" ()
    */
    public get phoneInput() : string {
        return this.get(this.phoneInputLanguageItemName);
    }

    /**
    /* "Popover" ()
    */
    public get popover() : string {
        return this.get(this.popoverLanguageItemName);
    }

    /**
    /* "Slider" ()
    */
    public get slider() : string {
        return this.get(this.sliderLanguageItemName);
    }

    /**
    /* "Spinner" ()
    */
    public get spinner() : string {
        return this.get(this.spinnerLanguageItemName);
    }

    /**
    /* "Switch" ()
    */
    public get switch() : string {
        return this.get(this.switchLanguageItemName);
    }

    /**
    /* "SwitchNullable" ()
    */
    public get switchNullable() : string {
        return this.get(this.switchNullableLanguageItemName);
    }

    /**
    /* "TabContainer" ()
    */
    public get tabContainer() : string {
        return this.get(this.tabContainerLanguageItemName);
    }

    /**
    /* "TextAreaInput" ()
    */
    public get textAreaInput() : string {
        return this.get(this.textAreaInputLanguageItemName);
    }

    /**
    /* "Layout.ThreeColumns" ()
    */
    public get layoutThreeColumns() : string {
        return this.get(this.layoutThreeColumnsLanguageItemName);
    }

    /**
    /* "Layout.TwoColumns" ()
    */
    public get layoutTwoColumns() : string {
        return this.get(this.layoutTwoColumnsLanguageItemName);
    }

    /**
    /* "CheckboxWidget" ()
    */
    public get checkboxWidget() : string {
        return this.get(this.checkboxWidgetLanguageItemName);
    }

    /**
    /* "CheckStepWidget" ()
    */
    public get checkStepWidget() : string {
        return this.get(this.checkStepWidgetLanguageItemName);
    }

    /**
    /* "DateInputWidget" ()
    */
    public get dateInputWidget() : string {
        return this.get(this.dateInputWidgetLanguageItemName);
    }

    /**
    /* "LinkWidget" ()
    */
    public get linkWidget() : string {
        return this.get(this.linkWidgetLanguageItemName);
    }

    /**
    /* "RouteWidget" ()
    */
    public get routeWidget() : string {
        return this.get(this.routeWidgetLanguageItemName);
    }

    /**
    /* "TimeWidget" ()
    */
    public get timeWidget() : string {
        return this.get(this.timeWidgetLanguageItemName);
    }

    /**
    /* "NumberWidget" ()
    */
    public get numberWidget() : string {
        return this.get(this.numberWidgetLanguageItemName);
    }

    /**
    /* "QrWidget.Scan.Error" (QR code scanner is not available, probably no permissions to camera on your mobile device.)
    */
    public get qrWidgetScanError() : string {
        return this.get(this.qrWidgetScanErrorLanguageItemName);
    }

    /**
    /* "SwitchWidget" ()
    */
    public get switchWidget() : string {
        return this.get(this.switchWidgetLanguageItemName);
    }

    /**
    /* "TextAreaWidget" ()
    */
    public get textAreaWidget() : string {
        return this.get(this.textAreaWidgetLanguageItemName);
    }

    /**
    /* "TextInputWidget" ()
    */
    public get textInputWidget() : string {
        return this.get(this.textInputWidgetLanguageItemName);
    }

    /**
    /* "StepsWidget" ()
    */
    public get stepsWidget() : string {
        return this.get(this.stepsWidgetLanguageItemName);
    }

    /**
    /* "TitleWidget" ()
    */
    public get titleWidget() : string {
        return this.get(this.titleWidgetLanguageItemName);
    }

    /**
    /* "Button" ()
    */
    public get button() : string {
        return this.get(this.buttonLanguageItemName);
    }

    /**
    /* "DateInput" ()
    */
    public get dateInput() : string {
        return this.get(this.dateInputLanguageItemName);
    }

    /**
    /* "Form" ()
    */
    public get form() : string {
        return this.get(this.formLanguageItemName);
    }

    /**
    /* "Layout" ()
    */
    public get layout() : string {
        return this.get(this.layoutLanguageItemName);
    }

    /**
    /* "WizardContainer" ()
    */
    public get wizardContainer() : string {
        return this.get(this.wizardContainerLanguageItemName);
    }

    /**
    /* "BaseInput.Validators.Required" ({0} is required)
    */
    public get baseInputValidatorsRequired() : string {
        return this.get(this.baseInputValidatorsRequiredLanguageItemName);
    }

    /**
    /* "BaseInput.Validators.Length" (Text is too short)
    */
    public get baseInputValidatorsLength() : string {
        return this.get(this.baseInputValidatorsLengthLanguageItemName);
    }

    /**
    /* "BaseInput.Validators.NumberRange" (Value must be in range {0} - {1})
    */
    public get baseInputValidatorsNumberRange() : string {
        return this.get(this.baseInputValidatorsNumberRangeLanguageItemName);
    }

    /**
    /* "BaseInput.Validators.DocumentTypeNotSupported" (Document type is not supported, choose file with extension {0})
    */
    public get baseInputValidatorsDocumentTypeNotSupported() : string {
        return this.get(this.baseInputValidatorsDocumentTypeNotSupportedLanguageItemName);
    }

    /**
    /* "BaseInput.Validators.DocumentTooBig" (Document file is too big)
    */
    public get baseInputValidatorsDocumentTooBig() : string {
        return this.get(this.baseInputValidatorsDocumentTooBigLanguageItemName);
    }

    /**
    /* "BaseInput.Validators.TotalSizeTooBig" (Total size of documents is too big)
    */
    public get baseInputValidatorsTotalSizeTooBig() : string {
        return this.get(this.baseInputValidatorsTotalSizeTooBigLanguageItemName);
    }

    /**
    /* "Month.January" (January)
    */
    public get monthJanuary() : string {
        return this.get(this.monthJanuaryLanguageItemName);
    }

    /**
    /* "Month.February" (February)
    */
    public get monthFebruary() : string {
        return this.get(this.monthFebruaryLanguageItemName);
    }

    /**
    /* "Month.March" (March)
    */
    public get monthMarch() : string {
        return this.get(this.monthMarchLanguageItemName);
    }

    /**
    /* "Month.April" (April)
    */
    public get monthApril() : string {
        return this.get(this.monthAprilLanguageItemName);
    }

    /**
    /* "Month.May" (May)
    */
    public get monthMay() : string {
        return this.get(this.monthMayLanguageItemName);
    }

    /**
    /* "Month.June" (June)
    */
    public get monthJune() : string {
        return this.get(this.monthJuneLanguageItemName);
    }

    /**
    /* "Month.July" (July)
    */
    public get monthJuly() : string {
        return this.get(this.monthJulyLanguageItemName);
    }

    /**
    /* "Month.August" (August)
    */
    public get monthAugust() : string {
        return this.get(this.monthAugustLanguageItemName);
    }

    /**
    /* "Month.September" (September)
    */
    public get monthSeptember() : string {
        return this.get(this.monthSeptemberLanguageItemName);
    }

    /**
    /* "Month.October" (October)
    */
    public get monthOctober() : string {
        return this.get(this.monthOctoberLanguageItemName);
    }

    /**
    /* "Month.November" (November)
    */
    public get monthNovember() : string {
        return this.get(this.monthNovemberLanguageItemName);
    }

    /**
    /* "Month.December" (December)
    */
    public get monthDecember() : string {
        return this.get(this.monthDecemberLanguageItemName);
    }
}

//Singleton
export default new ComponentsLocalizer();