//Autogenerated
import {BaseComponentsLocalizer} from "@weare/athenaeum-react-common";

class ComponentsLocalizer extends BaseComponentsLocalizer {

    //Constants
    public readonly dropdownMultipleSelectedLanguageItemName: string = `Dropdown.MultipleSelected`;
    public readonly footerContactLanguageItemName: string = `Footer.Contact`;
    public readonly footerFrontpageLanguageItemName: string = `Footer.Frontpage`;
    public readonly listLoadingLanguageItemName: string = `List.Loading`;
    public readonly signatureWidgetClearLanguageItemName: string = `SignatureWidget.Clear`;
    public readonly signatureWidgetDoneLanguageItemName: string = `SignatureWidget.Done`;
    public readonly modalSaveChangesLanguageItemName: string = `Modal.SaveChanges`;
    public readonly modalCloseLanguageItemName: string = `Modal.Close`;
    public readonly pageContainerPageHelpLanguageItemName: string = `PageContainer.PageHelp`;
    public readonly navigationWidgetPreviousLanguageItemName: string = `NavigationWidget.Previous`;
    public readonly navigationWidgetReturnToPreviousLanguageItemName: string = `NavigationWidget.ReturnToPrevious`;
    public readonly navigationWidgetNextLanguageItemName: string = `NavigationWidget.Next`;
    public readonly navigationWidgetGoToNextLanguageItemName: string = `NavigationWidget.GoToNext`;
    public readonly confirmationDialogAreYouSureLanguageItemName: string = `ConfirmationDialog.AreYouSure`;
    public readonly confirmationDialogConfirmButtonLanguageItemName: string = `ConfirmationDialog.ConfirmButton`;
    public readonly confirmationDialogCloseButtonLanguageItemName: string = `ConfirmationDialog.CloseButton`;
    public readonly confirmationDialogCommentLanguageItemName: string = `ConfirmationDialog.Comment`;
    public readonly formInputReceiverEmailLanguageItemName: string = `Form.Input.ReceiverEmail`;
    public readonly formInputPhoneLanguageItemName: string = `Form.Input.Phone`;
    public readonly formInputFirstnameLanguageItemName: string = `Form.Input.Firstname`;
    public readonly formInputMiddlenameLanguageItemName: string = `Form.Input.Middlename`;
    public readonly formInputLastnameLanguageItemName: string = `Form.Input.Lastname`;
    public readonly formInputMessageLanguageItemName: string = `Form.Input.Message`;
    public readonly addressDividerAddressLanguageItemName: string = `AddressDivider.Address`;
    public readonly virtualAddressDividerStreetLanguageItemName: string = `VirtualAddressDivider.Street`;
    public readonly virtualAddressDividerCityLanguageItemName: string = `VirtualAddressDivider.City`;
    public readonly virtualAddressDividerPostalcodeLanguageItemName: string = `VirtualAddressDivider.Postalcode`;
    public readonly formInputPostalboxLanguageItemName: string = `Form.Input.Postalbox`;
    public readonly formInputLanguageLanguageItemName: string = `Form.Input.Language`;
    public readonly formInputEmployeeNumberLanguageItemName: string = `Form.Input.EmployeeNumber`;
    public readonly formInputCostPoolLanguageItemName: string = `Form.Input.CostPool`;
    public readonly formInputWorkCardIdLanguageItemName: string = `Form.Input.WorkCardId`;
    public readonly formInputTimeTrackingDeviceIdLanguageItemName: string = `Form.Input.TimeTrackingDeviceId`;
    public readonly formInputContractSalaryHourlyPriceLanguageItemName: string = `Form.Input.ContractSalaryHourlyPrice`;
    public readonly formInputRoleLanguageItemName: string = `Form.Input.Role`;
    public readonly fileInputDragAndDropLanguageItemName: string = `FileInput.DragAndDrop`;
    public readonly fileInputReadonlyLanguageItemName: string = `FileInput.Readonly`;
    public readonly documentPreviewModalPreviewLanguageItemName: string = `DocumentPreviewModal.Preview`;
    public readonly fileInputChooseFileLanguageItemName: string = `FileInput.ChooseFile`;
    public readonly alertLanguageItemName: string = `Alert`;
    public readonly textInputLanguageItemName: string = `TextInput`;
    public readonly topNavLanguageItemName: string = `TopNav`;
    public readonly footerLanguageItemName: string = `Footer`;
    public readonly iconLanguageItemName: string = `Icon`;
    public readonly dropdownWidgetLanguageItemName: string = `DropdownWidget`;
    public readonly generalLanguageItemName: string = `General`;
    public readonly widgetContainerQrWidgetScanErrorLanguageItemName: string = `WidgetContainer.QrWidget.Scan.Error`;
    public readonly barWidgetBudgetDataModuleLabelLanguageItemName: string = `BarWidget.BudgetData.Module.Label`;
    public readonly barWidgetBudgetDataPerimeterFrameLabelLanguageItemName: string = `BarWidget.BudgetData.PerimeterFrame.Label`;
    public readonly barWidgetBudgetDataWeatherShelterLabelLanguageItemName: string = `BarWidget.BudgetData.WeatherShelter.Label`;
    public readonly locationPickerModalTitleLanguageItemName: string = `LocationPickerModal.Title`;
    public readonly locationPickerModalSubtitleLanguageItemName: string = `LocationPickerModal.Subtitle`;
    public readonly locationPickerModalSetLocationLanguageItemName: string = `LocationPickerModal.SetLocation`;
    public readonly dropdownNoItemsLanguageItemName: string = `Dropdown.NoItems`;
    public readonly dropdownNoDataLanguageItemName: string = `Dropdown.NoData`;
    public readonly dropdownFilterResultsLanguageItemName: string = `Dropdown.FilterResults`;
    public readonly dropdownGetResultsLanguageItemName: string = `Dropdown.GetResults`;
    public readonly dropdownAddLanguageItemName: string = `Dropdown.Add`;
    public readonly dropdownNothingSelectedLanguageItemName: string = `Dropdown.NothingSelected`;
    public readonly formInputEmailLanguageItemName: string = `Form.Input.Email`;
    public readonly passwordInputHelpTextLengthLanguageItemName: string = `PasswordInput.HelpText.Length`;
    public readonly documentPreviewModalDownloadLanguageItemName: string = `DocumentPreviewModal.Download`;
    public readonly fileInputPreviewLanguageItemName: string = `FileInput.Preview`;
    public readonly gridLanguageItemName: string = `Grid`;
    public readonly addressInputLanguageItemName: string = `AddressInput`;
    public readonly buttonContainerLanguageItemName: string = `ButtonContainer`;
    public readonly checkboxLanguageItemName: string = `Checkbox`;
    public readonly checkboxNullableLanguageItemName: string = `CheckboxNullable`;
    public readonly documentPreviewLanguageItemName: string = `DocumentPreview`;
    public readonly emailInputLanguageItemName: string = `EmailInput`;
    public readonly layoutFourColumnsLanguageItemName: string = `LayoutFourColumns`;
    public readonly linkLanguageItemName: string = `Link`;
    public readonly locationPickerLanguageItemName: string = `LocationPicker`;
    public readonly numberInputLanguageItemName: string = `NumberInput`;
    public readonly layoutOneColumnLanguageItemName: string = `LayoutOneColumn`;
    public readonly layoutInlineLanguageItemName: string = `LayoutInline`;
    public readonly paginationLanguageItemName: string = `Pagination`;
    public readonly phoneInputLanguageItemName: string = `PhoneInput`;
    public readonly popoverLanguageItemName: string = `Popover`;
    public readonly sliderLanguageItemName: string = `Slider`;
    public readonly spinnerLanguageItemName: string = `Spinner`;
    public readonly switchLanguageItemName: string = `Switch`;
    public readonly switchNullableLanguageItemName: string = `SwitchNullable`;
    public readonly tabContainerLanguageItemName: string = `TabContainer`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "fi", label: "Suomi" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" }
            ],
            "en");
        
        //Initializer
        this.set(this.dropdownMultipleSelectedLanguageItemName, { language: `en`, value: `{0} selected` }, { language: `sv`, value: `{0} valt` }, { language: `ru`, value: `{0} выбрано` }, { language: `pl`, value: `PL: {0} selected` }, { language: `fi`, value: `{0} valittu` },);
        this.set(this.footerContactLanguageItemName, { language: `en`, value: `Contact information` }, { language: `sv`, value: `Kontakt information` }, { language: `ru`, value: `Контактная информация` }, { language: `pl`, value: `PL: Contact information` }, { language: `fi`, value: `Yhteystiedot` },);
        this.set(this.footerFrontpageLanguageItemName, { language: `en`, value: `Frontpage` }, { language: `sv`, value: `Framsida` }, { language: `ru`, value: `RU: Frontpage` }, { language: `pl`, value: `PL: Frontpage` }, { language: `fi`, value: `Etusivu` },);
        this.set(this.listLoadingLanguageItemName, { language: `en`, value: `Loading...` }, { language: `sv`, value: `Laddar...` }, { language: `ru`, value: `Закрыть...` }, { language: `pl`, value: `PL: Loading...` }, { language: `fi`, value: `Ladataan...` },);
        this.set(this.signatureWidgetClearLanguageItemName, { language: `en`, value: `Clear` }, { language: `sv`, value: `Töm` }, { language: `ru`, value: `Очистить` }, { language: `pl`, value: `PL: Clear` }, { language: `fi`, value: `Tyhjennä` },);
        this.set(this.signatureWidgetDoneLanguageItemName, { language: `en`, value: `Done` }, { language: `sv`, value: `Färdig` }, { language: `ru`, value: `Завершить` }, { language: `pl`, value: `PL: Done` }, { language: `fi`, value: `Valmis` },);
        this.set(this.modalSaveChangesLanguageItemName, { language: `en`, value: `Save changes` }, { language: `sv`, value: `Spara ändringar` }, { language: `ru`, value: `Созранить изменения` }, { language: `pl`, value: `PL: Save changes` }, { language: `fi`, value: `Tallenna muutokset` },);
        this.set(this.modalCloseLanguageItemName, { language: `en`, value: `Close` }, { language: `sv`, value: `Stäng` }, { language: `ru`, value: `Закрыть` }, { language: `pl`, value: `PL: Close` }, { language: `fi`, value: `Sulje` },);
        this.set(this.pageContainerPageHelpLanguageItemName, { language: `en`, value: `Page help` }, { language: `sv`, value: `Sidhjälp` }, { language: `ru`, value: `Справка` }, { language: `pl`, value: `PL: Page help` }, { language: `fi`, value: `Sivun ohje` },);
        this.set(this.navigationWidgetPreviousLanguageItemName, { language: `en`, value: `Previous` }, { language: `sv`, value: `Föregående` }, { language: `ru`, value: `RU: Previous` }, { language: `pl`, value: `PL: Previous` }, { language: `fi`, value: `Edellinen` },);
        this.set(this.navigationWidgetReturnToPreviousLanguageItemName, { language: `en`, value: `Return to previous step` }, { language: `sv`, value: `Återgå till föregående steg` }, { language: `ru`, value: `RU: Return to previous step` }, { language: `pl`, value: `PL: Return to previous step` }, { language: `fi`, value: `Palaa edelliseen vaiheeseen` },);
        this.set(this.navigationWidgetNextLanguageItemName, { language: `en`, value: `Next` }, { language: `sv`, value: `Nästa` }, { language: `ru`, value: `RU: Next` }, { language: `pl`, value: `PL: Next` }, { language: `fi`, value: `Seuraava` },);
        this.set(this.navigationWidgetGoToNextLanguageItemName, { language: `en`, value: `Go to next step` }, { language: `sv`, value: `Gå till nästa steg` }, { language: `ru`, value: `RU: Go to next step` }, { language: `pl`, value: `PL: Go to next step` }, { language: `fi`, value: `Siirry seuraavaan vaiheeseen` },);
        this.set(this.confirmationDialogAreYouSureLanguageItemName, { language: `en`, value: `Are you sure?` }, { language: `sv`, value: `Är du säker?` }, { language: `ru`, value: `Вы уверены?` }, { language: `pl`, value: `PL: Are you sure?` }, { language: `fi`, value: `Oletko varma?` },);
        this.set(this.confirmationDialogConfirmButtonLanguageItemName, { language: `en`, value: `Confirm` }, { language: `sv`, value: `Bekräfta` }, { language: `ru`, value: `Подтвердить` }, { language: `pl`, value: `PL: Confirm` }, { language: `fi`, value: `Kyllä` },);
        this.set(this.confirmationDialogCloseButtonLanguageItemName, { language: `en`, value: `Close` }, { language: `sv`, value: `SV: Close` }, { language: `ru`, value: `Отмена` }, { language: `pl`, value: `PL: Close` }, { language: `fi`, value: `Ei` },);
        this.set(this.confirmationDialogCommentLanguageItemName, { language: `en`, value: `Please leave a comment` }, { language: `sv`, value: `Var vänlig och lämna en kommentar` }, { language: `ru`, value: `Пожалуйста, оставьте комментарий` }, { language: `pl`, value: `PL: Please leave a comment` }, { language: `fi`, value: `Ole hyvä ja kommentoi` },);
        this.set(this.formInputReceiverEmailLanguageItemName, { language: `en`, value: `Receiver email` }, { language: `sv`, value: `Epost` }, { language: `ru`, value: `RU: Receiver email` }, { language: `pl`, value: `PL: Receiver email` }, { language: `fi`, value: `Vastaanottaja` },);
        this.set(this.formInputPhoneLanguageItemName, { language: `en`, value: `Phone number` }, { language: `sv`, value: `Telefonnumer` }, { language: `ru`, value: `RU: Phone number` }, { language: `pl`, value: `PL: Phone number` }, { language: `fi`, value: `Puhelinnumero` },);
        this.set(this.formInputFirstnameLanguageItemName, { language: `en`, value: `Firstname` }, { language: `sv`, value: `Förnamn` }, { language: `ru`, value: `RU: Firstname` }, { language: `pl`, value: `PL: Firstname` }, { language: `fi`, value: `Etunimi` },);
        this.set(this.formInputMiddlenameLanguageItemName, { language: `en`, value: `Middle name` }, { language: `sv`, value: `SV: Middle name` }, { language: `ru`, value: `RU: Middle name` }, { language: `pl`, value: `PL: Middle name` }, { language: `fi`, value: `Toinen nimi` },);
        this.set(this.formInputLastnameLanguageItemName, { language: `en`, value: `Lastname` }, { language: `sv`, value: `Efternamn` }, { language: `ru`, value: `RU: Lastname` }, { language: `pl`, value: `PL: Lastname` }, { language: `fi`, value: `Sukunimi` },);
        this.set(this.formInputMessageLanguageItemName, { language: `en`, value: `Message` }, { language: `sv`, value: `Meddelande` }, { language: `ru`, value: `RU: Message` }, { language: `pl`, value: `PL: Message` }, { language: `fi`, value: `Viesti` },);
        this.set(this.addressDividerAddressLanguageItemName, { language: `en`, value: `Address` }, { language: `sv`, value: `Adress` }, { language: `ru`, value: `RU: Address` }, { language: `pl`, value: `PL: Address` }, { language: `fi`, value: `Osoite` },);
        this.set(this.virtualAddressDividerStreetLanguageItemName, { language: `en`, value: `Street` }, { language: `sv`, value: `Gata` }, { language: `ru`, value: `RU: Street` }, { language: `pl`, value: `PL: Street` }, { language: `fi`, value: `Katu` },);
        this.set(this.virtualAddressDividerCityLanguageItemName, { language: `en`, value: `City` }, { language: `sv`, value: `Stad` }, { language: `ru`, value: `RU: City` }, { language: `pl`, value: `PL: City` }, { language: `fi`, value: `Kaupunki` },);
        this.set(this.virtualAddressDividerPostalcodeLanguageItemName, { language: `en`, value: `Postal code` }, { language: `sv`, value: `Postnummer` }, { language: `ru`, value: `RU: Postal code` }, { language: `pl`, value: `PL: Postal code` }, { language: `fi`, value: `Postinumero` },);
        this.set(this.formInputPostalboxLanguageItemName, { language: `en`, value: `Postal box` }, { language: `sv`, value: `SV: Postal box` }, { language: `ru`, value: `RU: Postal box` }, { language: `pl`, value: `PL: Postal box` }, { language: `fi`, value: `Postilaatikko` },);
        this.set(this.formInputLanguageLanguageItemName, { language: `en`, value: `Language` }, { language: `sv`, value: `Språk` }, { language: `ru`, value: `RU: Language` }, { language: `pl`, value: `PL: Language` }, { language: `fi`, value: `Kieli` },);
        this.set(this.formInputEmployeeNumberLanguageItemName, { language: `en`, value: `Employee number` }, { language: `sv`, value: `Användar-id` }, { language: `ru`, value: `RU: Employee number` }, { language: `pl`, value: `PL: Employee number` }, { language: `fi`, value: `Käyttäjä-id` },);
        this.set(this.formInputCostPoolLanguageItemName, { language: `en`, value: `Cost pool` }, { language: `sv`, value: `Kostnadspool` }, { language: `ru`, value: `RU: Cost pool` }, { language: `pl`, value: `PL: Cost pool` }, { language: `fi`, value: `Kustannuspaikka` },);
        this.set(this.formInputWorkCardIdLanguageItemName, { language: `en`, value: `Work card id` }, { language: `sv`, value: `Arbetskorts-id` }, { language: `ru`, value: `RU: Work card id` }, { language: `pl`, value: `PL: Work card id` }, { language: `fi`, value: `Valttikorti-id` },);
        this.set(this.formInputTimeTrackingDeviceIdLanguageItemName, { language: `en`, value: `Time tracking device id` }, { language: `sv`, value: `SV: Time tracking device id` }, { language: `ru`, value: `RU: Time tracking device id` }, { language: `pl`, value: `PL: Time tracking device id` }, { language: `fi`, value: `Työaikaseurantalaite-id` },);
        this.set(this.formInputContractSalaryHourlyPriceLanguageItemName, { language: `en`, value: `Contract salary hourly price` }, { language: `sv`, value: `Kontrakt lön timpris` }, { language: `ru`, value: `RU: Contract salary hourly price` }, { language: `pl`, value: `PL: Contract salary hourly price` }, { language: `fi`, value: `Sopimuspalkan tuntihinta` },);
        this.set(this.formInputRoleLanguageItemName, { language: `en`, value: `Role` }, { language: `sv`, value: `Roll` }, { language: `ru`, value: `RU: Role` }, { language: `pl`, value: `PL: Role` }, { language: `fi`, value: `Rooli` },);
        this.set(this.fileInputDragAndDropLanguageItemName, { language: `en`, value: `Drag'n'drop file here, or click to select` }, { language: `sv`, value: `dra och släpp filen här, eller välj med att klicka` }, { language: `ru`, value: `RU: Drag'n'drop file here, or click to select` }, { language: `pl`, value: `PL: Drag'n'drop file here, or click to select` }, { language: `fi`, value: `Pudota tiedosto tähän tai valitse klikkaamalla` },);
        this.set(this.fileInputReadonlyLanguageItemName, { language: `en`, value: `File is readonly` }, { language: `sv`, value: `Filen är bara läsbar` }, { language: `ru`, value: `RU: File is readonly` }, { language: `pl`, value: `PL: File is readonly` }, { language: `fi`, value: `Tämä tiedosto on vain luettavissa` },);
        this.set(this.documentPreviewModalPreviewLanguageItemName, { language: `en`, value: `Preview` }, { language: `sv`, value: `Förhandsvisning` }, { language: `ru`, value: `RU: Preview` }, { language: `pl`, value: `PL: Preview` }, { language: `fi`, value: `Esikatselu` },);
        this.set(this.fileInputChooseFileLanguageItemName, { language: `en`, value: `Choose file` }, { language: `sv`, value: `Välj fil` }, { language: `ru`, value: `RU: Choose file` }, { language: `pl`, value: `PL: Choose file` }, { language: `fi`, value: `Valitse tiedosto` },);
        this.set(this.alertLanguageItemName, { language: `en`, value: `` }, { language: `sv`, value: `` }, { language: `ru`, value: `` }, { language: `pl`, value: `` }, { language: `fi`, value: `` },);
        this.set(this.textInputLanguageItemName, { language: `en`, value: `` }, { language: `sv`, value: `` }, { language: `ru`, value: `` }, { language: `pl`, value: `` }, { language: `fi`, value: `` },);
        this.set(this.topNavLanguageItemName, { language: `en`, value: `` }, { language: `sv`, value: `` }, { language: `ru`, value: `` }, { language: `pl`, value: `` }, { language: `fi`, value: `` },);
        this.set(this.footerLanguageItemName, { language: `en`, value: `` }, { language: `sv`, value: `` }, { language: `ru`, value: `` }, { language: `pl`, value: `` }, { language: `fi`, value: `` },);
        this.set(this.iconLanguageItemName, { language: `en`, value: `` }, { language: `sv`, value: `` }, { language: `ru`, value: `` }, { language: `pl`, value: `` }, { language: `fi`, value: `` },);
        this.set(this.dropdownWidgetLanguageItemName, { language: `en`, value: `` }, { language: `sv`, value: `` }, { language: `ru`, value: `` }, { language: `pl`, value: `` }, { language: `fi`, value: `` },);
        this.set(this.generalLanguageItemName, { language: `en`, value: `` }, { language: `sv`, value: `` }, { language: `ru`, value: `` }, { language: `pl`, value: `` }, { language: `fi`, value: `` },);
        this.set(this.widgetContainerQrWidgetScanErrorLanguageItemName, { language: `en`, value: `QR code scanner is not available, probably no permissions to camera on your mobile device.` }, { language: `sv`, value: `QR-kodskanner inte tillgänglig, förmodligen inga behörigheter för kameran på din mobila enhet.` }, { language: `ru`, value: `RU: QR code scanner not available, probably no permissions to camera on you mobile device.` }, { language: `pl`, value: `PL: QR code scanner not available, probably no permissions to camera on you mobile device.` }, { language: `fi`, value: `QR koodi skanneri ei käytössä. Mahdollisesti kameran käyttöoikeudet puuttuvat laitteeltasi.` },);
        this.set(this.barWidgetBudgetDataModuleLabelLanguageItemName, { language: `en`, value: `Module` }, { language: `sv`, value: `SV: Module` }, { language: `ru`, value: `RU: Module` }, { language: `pl`, value: `PL: Module` }, { language: `fi`, value: `Moduuli` },);
        this.set(this.barWidgetBudgetDataPerimeterFrameLabelLanguageItemName, { language: `en`, value: `Perimeter frame` }, { language: `sv`, value: `SV: Perimeter frame` }, { language: `ru`, value: `RU: Perimeter frame` }, { language: `pl`, value: `PL: Perimeter frame` }, { language: `fi`, value: `Kehäteline` },);
        this.set(this.barWidgetBudgetDataWeatherShelterLabelLanguageItemName, { language: `en`, value: `Weather shelter` }, { language: `sv`, value: `SV: Weather shelter` }, { language: `ru`, value: `RU: Weather shelter` }, { language: `pl`, value: `PL: Weather shelter` }, { language: `fi`, value: `Sääsuoja` },);
        this.set(this.locationPickerModalTitleLanguageItemName, { language: `en`, value: `Location picker` }, { language: `sv`, value: `Platsväljare` }, { language: `ru`, value: `RU: Location picker` }, { language: `pl`, value: `PL: Location picker` }, { language: `fi`, value: `Sijaintivalitsin` },);
        this.set(this.locationPickerModalSubtitleLanguageItemName, { language: `en`, value: `Choose location on map` }, { language: `sv`, value: `Välj plats på kartan` }, { language: `ru`, value: `RU: Choose location on map` }, { language: `pl`, value: `PL: Choose location on map` }, { language: `fi`, value: `Valitse sijainti kartalla` },);
        this.set(this.locationPickerModalSetLocationLanguageItemName, { language: `en`, value: `Set location` }, { language: `sv`, value: `SV: Set location` }, { language: `ru`, value: `RU: Set location` }, { language: `pl`, value: `Ställ in plats` }, { language: `fi`, value: `Aseta sijainti` },);
        this.set(this.dropdownNoItemsLanguageItemName, { language: `en`, value: `No items found` }, { language: `sv`, value: `Inga objekt hittades` }, { language: `ru`, value: `Данные не найдены` }, { language: `pl`, value: `PL: No items found` }, { language: `fi`, value: `Kohteita ei löytynyt` },);
        this.set(this.dropdownNoDataLanguageItemName, { language: `en`, value: `No data` }, { language: `sv`, value: `Ingen information` }, { language: `ru`, value: `Нет данных` }, { language: `pl`, value: `PL: No data` }, { language: `fi`, value: `Ei tietoja` },);
        this.set(this.dropdownFilterResultsLanguageItemName, { language: `en`, value: `Filter results` }, { language: `sv`, value: `Filtrera resultat` }, { language: `ru`, value: `RU: Filter results` }, { language: `pl`, value: `PL: Filter results` }, { language: `fi`, value: `Suodata tulokset` },);
        this.set(this.dropdownGetResultsLanguageItemName, { language: `en`, value: `Start typing to get results` }, { language: `sv`, value: `Börja skriva för att få resultat` }, { language: `ru`, value: `Начните писать, чтобы увидеть данные` }, { language: `pl`, value: `PL: Start typing to get results` }, { language: `fi`, value: `Aloita kirjoittaminen saadaksesi tuloksia` },);
        this.set(this.dropdownAddLanguageItemName, { language: `en`, value: `Add` }, { language: `sv`, value: `SV: Add` }, { language: `ru`, value: `Новый` }, { language: `pl`, value: `PL: Add` }, { language: `fi`, value: `Lisää` },);
        this.set(this.dropdownNothingSelectedLanguageItemName, { language: `en`, value: `Nothing is selected` }, { language: `sv`, value: `Ingenting är valt` }, { language: `ru`, value: `RU: Nothing is selected` }, { language: `pl`, value: `PL: Nothing is selected` }, { language: `fi`, value: `Ei mitään valittu` },);
        this.set(this.formInputEmailLanguageItemName, { language: `en`, value: `Email` }, { language: `sv`, value: `Epost` }, { language: `ru`, value: `RU: Email` }, { language: `pl`, value: `PL: Email` }, { language: `fi`, value: `Sähköposti` },);
        this.set(this.passwordInputHelpTextLengthLanguageItemName, { language: `en`, value: `at least 8 characters long` }, { language: `sv`, value: `åtminstone 8 tecken` }, { language: `ru`, value: `RU: at least 8 characters long` }, { language: `pl`, value: `PL: at least 8 characters long` }, { language: `fi`, value: `vähintään 8 merkkiä` },);
        this.set(this.documentPreviewModalDownloadLanguageItemName, { language: `en`, value: `Download` }, { language: `sv`, value: `SV: Download` }, { language: `ru`, value: `RU: Download` }, { language: `pl`, value: `PL: Download` }, { language: `fi`, value: `FI: Download` },);
        this.set(this.fileInputPreviewLanguageItemName, { language: `en`, value: `Preview` }, { language: `sv`, value: `Förhandsvisning` }, { language: `ru`, value: `RU: Preview` }, { language: `pl`, value: `PL: Preview` }, { language: `fi`, value: `Esikatselu` },);
        this.set(this.gridLanguageItemName, { language: `en`, value: `` },);
        this.set(this.addressInputLanguageItemName, { language: `en`, value: `` },);
        this.set(this.buttonContainerLanguageItemName, { language: `en`, value: `` },);
        this.set(this.checkboxLanguageItemName, { language: `en`, value: `` },);
        this.set(this.checkboxNullableLanguageItemName, { language: `en`, value: `` },);
        this.set(this.documentPreviewLanguageItemName, { language: `en`, value: `` },);
        this.set(this.emailInputLanguageItemName, { language: `en`, value: `` },);
        this.set(this.layoutFourColumnsLanguageItemName, { language: `en`, value: `` },);
        this.set(this.linkLanguageItemName, { language: `en`, value: `` },);
        this.set(this.locationPickerLanguageItemName, { language: `en`, value: `` },);
        this.set(this.numberInputLanguageItemName, { language: `en`, value: `` },);
        this.set(this.layoutOneColumnLanguageItemName, { language: `en`, value: `` },);
        this.set(this.layoutInlineLanguageItemName, { language: `en`, value: `` },);
        this.set(this.paginationLanguageItemName, { language: `en`, value: `` },);
        this.set(this.phoneInputLanguageItemName, { language: `en`, value: `` },);
        this.set(this.popoverLanguageItemName, { language: `en`, value: `` },);
        this.set(this.sliderLanguageItemName, { language: `en`, value: `` },);
        this.set(this.spinnerLanguageItemName, { language: `en`, value: `` },);
        this.set(this.switchLanguageItemName, { language: `en`, value: `` },);
        this.set(this.switchNullableLanguageItemName, { language: `en`, value: `` },);
        this.set(this.tabContainerLanguageItemName, { language: `en`, value: `` },);
    }

    /**
    /* "Dropdown.MultipleSelected" ({0} selected)
    */
    public get dropdownMultipleSelected() : string {
        return this.get(this.dropdownMultipleSelectedLanguageItemName);
    }

    /**
    /* "Footer.Contact" (Contact information)
    */
    public get footerContact() : string {
        return this.get(this.footerContactLanguageItemName);
    }

    /**
    /* "Footer.Frontpage" (Frontpage)
    */
    public get footerFrontpage() : string {
        return this.get(this.footerFrontpageLanguageItemName);
    }

    /**
    /* "List.Loading" (Loading...)
    */
    public get listLoading() : string {
        return this.get(this.listLoadingLanguageItemName);
    }

    /**
    /* "SignatureWidget.Clear" (Clear)
    */
    public get signatureWidgetClear() : string {
        return this.get(this.signatureWidgetClearLanguageItemName);
    }

    /**
    /* "SignatureWidget.Done" (Done)
    */
    public get signatureWidgetDone() : string {
        return this.get(this.signatureWidgetDoneLanguageItemName);
    }

    /**
    /* "Modal.SaveChanges" (Save changes)
    */
    public get modalSaveChanges() : string {
        return this.get(this.modalSaveChangesLanguageItemName);
    }

    /**
    /* "Modal.Close" (Close)
    */
    public get modalClose() : string {
        return this.get(this.modalCloseLanguageItemName);
    }

    /**
    /* "PageContainer.PageHelp" (Page help)
    */
    public get pageContainerPageHelp() : string {
        return this.get(this.pageContainerPageHelpLanguageItemName);
    }

    /**
    /* "NavigationWidget.Previous" (Previous)
    */
    public get navigationWidgetPrevious() : string {
        return this.get(this.navigationWidgetPreviousLanguageItemName);
    }

    /**
    /* "NavigationWidget.ReturnToPrevious" (Return to previous step)
    */
    public get navigationWidgetReturnToPrevious() : string {
        return this.get(this.navigationWidgetReturnToPreviousLanguageItemName);
    }

    /**
    /* "NavigationWidget.Next" (Next)
    */
    public get navigationWidgetNext() : string {
        return this.get(this.navigationWidgetNextLanguageItemName);
    }

    /**
    /* "NavigationWidget.GoToNext" (Go to next step)
    */
    public get navigationWidgetGoToNext() : string {
        return this.get(this.navigationWidgetGoToNextLanguageItemName);
    }

    /**
    /* "ConfirmationDialog.AreYouSure" (Are you sure?)
    */
    public get confirmationDialogAreYouSure() : string {
        return this.get(this.confirmationDialogAreYouSureLanguageItemName);
    }

    /**
    /* "ConfirmationDialog.ConfirmButton" (Confirm)
    */
    public get confirmationDialogConfirmButton() : string {
        return this.get(this.confirmationDialogConfirmButtonLanguageItemName);
    }

    /**
    /* "ConfirmationDialog.CloseButton" (Close)
    */
    public get confirmationDialogCloseButton() : string {
        return this.get(this.confirmationDialogCloseButtonLanguageItemName);
    }

    /**
    /* "ConfirmationDialog.Comment" (Please leave a comment)
    */
    public get confirmationDialogComment() : string {
        return this.get(this.confirmationDialogCommentLanguageItemName);
    }

    /**
    /* "Form.Input.ReceiverEmail" (Receiver email)
    */
    public get formInputReceiverEmail() : string {
        return this.get(this.formInputReceiverEmailLanguageItemName);
    }

    /**
    /* "Form.Input.Phone" (Phone number)
    */
    public get formInputPhone() : string {
        return this.get(this.formInputPhoneLanguageItemName);
    }

    /**
    /* "Form.Input.Firstname" (Firstname)
    */
    public get formInputFirstname() : string {
        return this.get(this.formInputFirstnameLanguageItemName);
    }

    /**
    /* "Form.Input.Middlename" (Middle name)
    */
    public get formInputMiddlename() : string {
        return this.get(this.formInputMiddlenameLanguageItemName);
    }

    /**
    /* "Form.Input.Lastname" (Lastname)
    */
    public get formInputLastname() : string {
        return this.get(this.formInputLastnameLanguageItemName);
    }

    /**
    /* "Form.Input.Message" (Message)
    */
    public get formInputMessage() : string {
        return this.get(this.formInputMessageLanguageItemName);
    }

    /**
    /* "AddressDivider.Address" (Address)
    */
    public get addressDividerAddress() : string {
        return this.get(this.addressDividerAddressLanguageItemName);
    }

    /**
    /* "VirtualAddressDivider.Street" (Street)
    */
    public get virtualAddressDividerStreet() : string {
        return this.get(this.virtualAddressDividerStreetLanguageItemName);
    }

    /**
    /* "VirtualAddressDivider.City" (City)
    */
    public get virtualAddressDividerCity() : string {
        return this.get(this.virtualAddressDividerCityLanguageItemName);
    }

    /**
    /* "VirtualAddressDivider.Postalcode" (Postal code)
    */
    public get virtualAddressDividerPostalcode() : string {
        return this.get(this.virtualAddressDividerPostalcodeLanguageItemName);
    }

    /**
    /* "Form.Input.Postalbox" (Postal box)
    */
    public get formInputPostalbox() : string {
        return this.get(this.formInputPostalboxLanguageItemName);
    }

    /**
    /* "Form.Input.Language" (Language)
    */
    public get formInputLanguage() : string {
        return this.get(this.formInputLanguageLanguageItemName);
    }

    /**
    /* "Form.Input.EmployeeNumber" (Employee number)
    */
    public get formInputEmployeeNumber() : string {
        return this.get(this.formInputEmployeeNumberLanguageItemName);
    }

    /**
    /* "Form.Input.CostPool" (Cost pool)
    */
    public get formInputCostPool() : string {
        return this.get(this.formInputCostPoolLanguageItemName);
    }

    /**
    /* "Form.Input.WorkCardId" (Work card id)
    */
    public get formInputWorkCardId() : string {
        return this.get(this.formInputWorkCardIdLanguageItemName);
    }

    /**
    /* "Form.Input.TimeTrackingDeviceId" (Time tracking device id)
    */
    public get formInputTimeTrackingDeviceId() : string {
        return this.get(this.formInputTimeTrackingDeviceIdLanguageItemName);
    }

    /**
    /* "Form.Input.ContractSalaryHourlyPrice" (Contract salary hourly price)
    */
    public get formInputContractSalaryHourlyPrice() : string {
        return this.get(this.formInputContractSalaryHourlyPriceLanguageItemName);
    }

    /**
    /* "Form.Input.Role" (Role)
    */
    public get formInputRole() : string {
        return this.get(this.formInputRoleLanguageItemName);
    }

    /**
    /* "FileInput.DragAndDrop" (Drag'n'drop file here, or click to select)
    */
    public get fileInputDragAndDrop() : string {
        return this.get(this.fileInputDragAndDropLanguageItemName);
    }

    /**
    /* "FileInput.Readonly" (File is readonly)
    */
    public get fileInputReadonly() : string {
        return this.get(this.fileInputReadonlyLanguageItemName);
    }

    /**
    /* "DocumentPreviewModal.Preview" (Preview)
    */
    public get documentPreviewModalPreview() : string {
        return this.get(this.documentPreviewModalPreviewLanguageItemName);
    }

    /**
    /* "FileInput.ChooseFile" (Choose file)
    */
    public get fileInputChooseFile() : string {
        return this.get(this.fileInputChooseFileLanguageItemName);
    }

    /**
    /* "Alert" ()
    */
    public get alert() : string {
        return this.get(this.alertLanguageItemName);
    }

    /**
    /* "TextInput" ()
    */
    public get textInput() : string {
        return this.get(this.textInputLanguageItemName);
    }

    /**
    /* "TopNav" ()
    */
    public get topNav() : string {
        return this.get(this.topNavLanguageItemName);
    }

    /**
    /* "Footer" ()
    */
    public get footer() : string {
        return this.get(this.footerLanguageItemName);
    }

    /**
    /* "Icon" ()
    */
    public get icon() : string {
        return this.get(this.iconLanguageItemName);
    }

    /**
    /* "DropdownWidget" ()
    */
    public get dropdownWidget() : string {
        return this.get(this.dropdownWidgetLanguageItemName);
    }

    /**
    /* "General" ()
    */
    public get general() : string {
        return this.get(this.generalLanguageItemName);
    }

    /**
    /* "WidgetContainer.QrWidget.Scan.Error" (QR code scanner is not available, probably no permissions to camera on your mobile device.)
    */
    public get widgetContainerQrWidgetScanError() : string {
        return this.get(this.widgetContainerQrWidgetScanErrorLanguageItemName);
    }

    /**
    /* "BarWidget.BudgetData.Module.Label" (Module)
    */
    public get barWidgetBudgetDataModuleLabel() : string {
        return this.get(this.barWidgetBudgetDataModuleLabelLanguageItemName);
    }

    /**
    /* "BarWidget.BudgetData.PerimeterFrame.Label" (Perimeter frame)
    */
    public get barWidgetBudgetDataPerimeterFrameLabel() : string {
        return this.get(this.barWidgetBudgetDataPerimeterFrameLabelLanguageItemName);
    }

    /**
    /* "BarWidget.BudgetData.WeatherShelter.Label" (Weather shelter)
    */
    public get barWidgetBudgetDataWeatherShelterLabel() : string {
        return this.get(this.barWidgetBudgetDataWeatherShelterLabelLanguageItemName);
    }

    /**
    /* "LocationPickerModal.Title" (Location picker)
    */
    public get locationPickerModalTitle() : string {
        return this.get(this.locationPickerModalTitleLanguageItemName);
    }

    /**
    /* "LocationPickerModal.Subtitle" (Choose location on map)
    */
    public get locationPickerModalSubtitle() : string {
        return this.get(this.locationPickerModalSubtitleLanguageItemName);
    }

    /**
    /* "LocationPickerModal.SetLocation" (Set location)
    */
    public get locationPickerModalSetLocation() : string {
        return this.get(this.locationPickerModalSetLocationLanguageItemName);
    }

    /**
    /* "Dropdown.NoItems" (No items found)
    */
    public get dropdownNoItems() : string {
        return this.get(this.dropdownNoItemsLanguageItemName);
    }

    /**
    /* "Dropdown.NoData" (No data)
    */
    public get dropdownNoData() : string {
        return this.get(this.dropdownNoDataLanguageItemName);
    }

    /**
    /* "Dropdown.FilterResults" (Filter results)
    */
    public get dropdownFilterResults() : string {
        return this.get(this.dropdownFilterResultsLanguageItemName);
    }

    /**
    /* "Dropdown.GetResults" (Start typing to get results)
    */
    public get dropdownGetResults() : string {
        return this.get(this.dropdownGetResultsLanguageItemName);
    }

    /**
    /* "Dropdown.Add" (Add)
    */
    public get dropdownAdd() : string {
        return this.get(this.dropdownAddLanguageItemName);
    }

    /**
    /* "Dropdown.NothingSelected" (Nothing is selected)
    */
    public get dropdownNothingSelected() : string {
        return this.get(this.dropdownNothingSelectedLanguageItemName);
    }

    /**
    /* "Form.Input.Email" (Email)
    */
    public get formInputEmail() : string {
        return this.get(this.formInputEmailLanguageItemName);
    }

    /**
    /* "PasswordInput.HelpText.Length" (at least 8 characters long)
    */
    public get passwordInputHelpTextLength() : string {
        return this.get(this.passwordInputHelpTextLengthLanguageItemName);
    }

    /**
    /* "DocumentPreviewModal.Download" (Download)
    */
    public get documentPreviewModalDownload() : string {
        return this.get(this.documentPreviewModalDownloadLanguageItemName);
    }

    /**
    /* "FileInput.Preview" (Preview)
    */
    public get fileInputPreview() : string {
        return this.get(this.fileInputPreviewLanguageItemName);
    }

    /**
    /* "Grid" ()
    */
    public get grid() : string {
        return this.get(this.gridLanguageItemName);
    }

    /**
    /* "AddressInput" ()
    */
    public get addressInput() : string {
        return this.get(this.addressInputLanguageItemName);
    }

    /**
    /* "ButtonContainer" ()
    */
    public get buttonContainer() : string {
        return this.get(this.buttonContainerLanguageItemName);
    }

    /**
    /* "Checkbox" ()
    */
    public get checkbox() : string {
        return this.get(this.checkboxLanguageItemName);
    }

    /**
    /* "CheckboxNullable" ()
    */
    public get checkboxNullable() : string {
        return this.get(this.checkboxNullableLanguageItemName);
    }

    /**
    /* "DocumentPreview" ()
    */
    public get documentPreview() : string {
        return this.get(this.documentPreviewLanguageItemName);
    }

    /**
    /* "EmailInput" ()
    */
    public get emailInput() : string {
        return this.get(this.emailInputLanguageItemName);
    }

    /**
    /* "LayoutFourColumns" ()
    */
    public get layoutFourColumns() : string {
        return this.get(this.layoutFourColumnsLanguageItemName);
    }

    /**
    /* "Link" ()
    */
    public get link() : string {
        return this.get(this.linkLanguageItemName);
    }

    /**
    /* "LocationPicker" ()
    */
    public get locationPicker() : string {
        return this.get(this.locationPickerLanguageItemName);
    }

    /**
    /* "NumberInput" ()
    */
    public get numberInput() : string {
        return this.get(this.numberInputLanguageItemName);
    }

    /**
    /* "LayoutOneColumn" ()
    */
    public get layoutOneColumn() : string {
        return this.get(this.layoutOneColumnLanguageItemName);
    }

    /**
    /* "LayoutInline" ()
    */
    public get layoutInline() : string {
        return this.get(this.layoutInlineLanguageItemName);
    }

    /**
    /* "Pagination" ()
    */
    public get pagination() : string {
        return this.get(this.paginationLanguageItemName);
    }

    /**
    /* "PhoneInput" ()
    */
    public get phoneInput() : string {
        return this.get(this.phoneInputLanguageItemName);
    }

    /**
    /* "Popover" ()
    */
    public get popover() : string {
        return this.get(this.popoverLanguageItemName);
    }

    /**
    /* "Slider" ()
    */
    public get slider() : string {
        return this.get(this.sliderLanguageItemName);
    }

    /**
    /* "Spinner" ()
    */
    public get spinner() : string {
        return this.get(this.spinnerLanguageItemName);
    }

    /**
    /* "Switch" ()
    */
    public get switch() : string {
        return this.get(this.switchLanguageItemName);
    }

    /**
    /* "SwitchNullable" ()
    */
    public get switchNullable() : string {
        return this.get(this.switchNullableLanguageItemName);
    }

    /**
    /* "TabContainer" ()
    */
    public get tabContainer() : string {
        return this.get(this.tabContainerLanguageItemName);
    }
}

//Singleton
export default new ComponentsLocalizer();