//Autogenerated
import {BaseComponentsLocalizer} from "@weare/athenaeum-react-common";

class ComponentsLocalizer extends BaseComponentsLocalizer {

    //Constants
    public readonly dropdownNoItemsLanguageItemName: string = `Dropdown.NoItems`;
    public readonly dropdownNoDataLanguageItemName: string = `Dropdown.NoData`;
    public readonly dropdownFilterResultsLanguageItemName: string = `Dropdown.FilterResults`;
    public readonly dropdownGetResultsLanguageItemName: string = `Dropdown.GetResults`;
    public readonly dropdownAddLanguageItemName: string = `Dropdown.Add`;
    public readonly dropdownNothingSelectedLanguageItemName: string = `Dropdown.NothingSelected`;
    public readonly dropdownMultipleSelectedLanguageItemName: string = `Dropdown.MultipleSelected`;
    public readonly footerContactLanguageItemName: string = `Footer.Contact`;
    public readonly footerFrontpageLanguageItemName: string = `Footer.Frontpage`;
    public readonly listLoadingLanguageItemName: string = `List.Loading`;
    public readonly signatureWidgetClearLanguageItemName: string = `SignatureWidget.Clear`;
    public readonly signatureWidgetDoneLanguageItemName: string = `SignatureWidget.Done`;
    public readonly modalSaveChangesLanguageItemName: string = `Modal.SaveChanges`;
    public readonly modalCloseLanguageItemName: string = `Modal.Close`;
    public readonly pageContainerPageHelpLanguageItemName: string = `PageContainer.PageHelp`;
    public readonly navigationWidgetPreviousLanguageItemName: string = `NavigationWidget.Previous`;
    public readonly navigationWidgetReturnToPreviousLanguageItemName: string = `NavigationWidget.ReturnToPrevious`;
    public readonly navigationWidgetNextLanguageItemName: string = `NavigationWidget.Next`;
    public readonly navigationWidgetGoToNextLanguageItemName: string = `NavigationWidget.GoToNext`;
    public readonly confirmationDialogAreYouSureLanguageItemName: string = `ConfirmationDialog.AreYouSure`;
    public readonly confirmationDialogConfirmButtonLanguageItemName: string = `ConfirmationDialog.ConfirmButton`;
    public readonly confirmationDialogCloseButtonLanguageItemName: string = `ConfirmationDialog.CloseButton`;
    public readonly confirmationDialogCommentLanguageItemName: string = `ConfirmationDialog.Comment`;
    public readonly alertLanguageItemName: string = `Alert`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "fi", label: "Suomi" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" }
            ],
            "en");
        
        //Initializer
        this.set(this.dropdownNoItemsLanguageItemName, { language: `en`, value: `No items found` }, { language: `sv`, value: `Inga objekt hittades` }, { language: `ru`, value: `RU: No items found` }, { language: `pl`, value: `PL: No items found` }, { language: `fi`, value: `Kohteita ei löytynyt` },);
        this.set(this.dropdownNoDataLanguageItemName, { language: `en`, value: `No data` }, { language: `sv`, value: `Ingen information` }, { language: `ru`, value: `RU: No data` }, { language: `pl`, value: `PL: No data` }, { language: `fi`, value: `Ei tietoja` },);
        this.set(this.dropdownFilterResultsLanguageItemName, { language: `en`, value: `Filter results` }, { language: `sv`, value: `Filtrera resultat` }, { language: `ru`, value: `RU: Filter results` }, { language: `pl`, value: `PL: Filter results` }, { language: `fi`, value: `Suodata tulokset` },);
        this.set(this.dropdownGetResultsLanguageItemName, { language: `en`, value: `Start typing to get results` }, { language: `sv`, value: `Börja skriva för att få resultat` }, { language: `ru`, value: `RU: Start typing to get results` }, { language: `pl`, value: `PL: Start typing to get results` }, { language: `fi`, value: `Aloita kirjoittaminen saadaksesi tuloksia` },);
        this.set(this.dropdownAddLanguageItemName, { language: `en`, value: `Add` }, { language: `sv`, value: `SV: Add` }, { language: `ru`, value: `RU: Add` }, { language: `pl`, value: `PL: Add` }, { language: `fi`, value: `Lisää` },);
        this.set(this.dropdownNothingSelectedLanguageItemName, { language: `en`, value: `Nothing is selected` }, { language: `sv`, value: `Ingenting är valt` }, { language: `ru`, value: `RU: Nothing is selected` }, { language: `pl`, value: `PL: Nothing is selected` }, { language: `fi`, value: `Ei mitään valittu` },);
        this.set(this.dropdownMultipleSelectedLanguageItemName, { language: `en`, value: `{0} selected` }, { language: `sv`, value: `{0} valt` }, { language: `ru`, value: `RU: {0} selected` }, { language: `pl`, value: `PL: {0} selected` }, { language: `fi`, value: `{0} valittu` },);
        this.set(this.footerContactLanguageItemName, { language: `en`, value: `Contact information` }, { language: `sv`, value: `Kontakt information` }, { language: `ru`, value: `RU: Contact information` }, { language: `pl`, value: `PL: Contact information` }, { language: `fi`, value: `Yhteystiedot` },);
        this.set(this.footerFrontpageLanguageItemName, { language: `en`, value: `Frontpage` }, { language: `sv`, value: `Framsida` }, { language: `ru`, value: `RU: Frontpage` }, { language: `pl`, value: `PL: Frontpage` }, { language: `fi`, value: `Etusivu` },);
        this.set(this.listLoadingLanguageItemName, { language: `en`, value: `Loading...` }, { language: `sv`, value: `Laddar...` }, { language: `ru`, value: `RU: Loading...` }, { language: `pl`, value: `PL: Loading...` }, { language: `fi`, value: `Ladataan...` },);
        this.set(this.signatureWidgetClearLanguageItemName, { language: `en`, value: `Clear` }, { language: `sv`, value: `Töm` }, { language: `ru`, value: `RU: Clear` }, { language: `pl`, value: `PL: Clear` }, { language: `fi`, value: `Tyhjennä` },);
        this.set(this.signatureWidgetDoneLanguageItemName, { language: `en`, value: `Done` }, { language: `sv`, value: `Färdig` }, { language: `ru`, value: `RU: Done` }, { language: `pl`, value: `PL: Done` }, { language: `fi`, value: `Valmis` },);
        this.set(this.modalSaveChangesLanguageItemName, { language: `en`, value: `Save changes` }, { language: `sv`, value: `Spara ändringar` }, { language: `ru`, value: `RU: Save changes` }, { language: `pl`, value: `PL: Save changes` }, { language: `fi`, value: `Tallenna muutokset` },);
        this.set(this.modalCloseLanguageItemName, { language: `en`, value: `Close` }, { language: `sv`, value: `Stäng` }, { language: `ru`, value: `RU: Close` }, { language: `pl`, value: `PL: Close` }, { language: `fi`, value: `Sulje` },);
        this.set(this.pageContainerPageHelpLanguageItemName, { language: `en`, value: `Page help` }, { language: `sv`, value: `Sidhjälp` }, { language: `ru`, value: `RU: Page help` }, { language: `pl`, value: `PL: Page help` }, { language: `fi`, value: `Sivun ohje` },);
        this.set(this.navigationWidgetPreviousLanguageItemName, { language: `en`, value: `Previous` }, { language: `sv`, value: `Föregående` }, { language: `ru`, value: `RU: Previous` }, { language: `pl`, value: `PL: Previous` }, { language: `fi`, value: `Edellinen` },);
        this.set(this.navigationWidgetReturnToPreviousLanguageItemName, { language: `en`, value: `Return to previous step` }, { language: `sv`, value: `Återgå till föregående steg` }, { language: `ru`, value: `RU: Return to previous step` }, { language: `pl`, value: `PL: Return to previous step` }, { language: `fi`, value: `Palaa edelliseen vaiheeseen` },);
        this.set(this.navigationWidgetNextLanguageItemName, { language: `en`, value: `Next` }, { language: `sv`, value: `Nästa` }, { language: `ru`, value: `RU: Next` }, { language: `pl`, value: `PL: Next` }, { language: `fi`, value: `Seuraava` },);
        this.set(this.navigationWidgetGoToNextLanguageItemName, { language: `en`, value: `Go to next step` }, { language: `sv`, value: `Gå till nästa steg` }, { language: `ru`, value: `RU: Go to next step` }, { language: `pl`, value: `PL: Go to next step` }, { language: `fi`, value: `Siirry seuraavaan vaiheeseen` },);
        this.set(this.confirmationDialogAreYouSureLanguageItemName, { language: `en`, value: `Are you sure?` }, { language: `sv`, value: `Är du säker?` }, { language: `ru`, value: `RU: Are you sure?` }, { language: `pl`, value: `PL: Are you sure?` }, { language: `fi`, value: `Oletko varma?` },);
        this.set(this.confirmationDialogConfirmButtonLanguageItemName, { language: `en`, value: `Confirm` }, { language: `sv`, value: `Bekräfta` }, { language: `fi`, value: `Kyllä` },);
        this.set(this.confirmationDialogCloseButtonLanguageItemName, { language: `en`, value: `Close` }, { language: `sv`, value: `Stäng` }, { language: `ru`, value: `Close` }, { language: `fi`, value: `Ei` },);
        this.set(this.confirmationDialogCommentLanguageItemName, { language: `en`, value: `Please leave a comment` }, { language: `sv`, value: `Var vänlig och lämna en kommentar` }, { language: `fi`, value: `Ole hyvä ja kommentoi` },);
        this.set(this.alertLanguageItemName, { language: `en`, value: `` },);
    }

    /**
    /* "Dropdown.NoItems" (No items found)
    */
    public get dropdownNoItems() : string {
        return this.get(this.dropdownNoItemsLanguageItemName);
    }

    /**
    /* "Dropdown.NoData" (No data)
    */
    public get dropdownNoData() : string {
        return this.get(this.dropdownNoDataLanguageItemName);
    }

    /**
    /* "Dropdown.FilterResults" (Filter results)
    */
    public get dropdownFilterResults() : string {
        return this.get(this.dropdownFilterResultsLanguageItemName);
    }

    /**
    /* "Dropdown.GetResults" (Start typing to get results)
    */
    public get dropdownGetResults() : string {
        return this.get(this.dropdownGetResultsLanguageItemName);
    }

    /**
    /* "Dropdown.Add" (Add)
    */
    public get dropdownAdd() : string {
        return this.get(this.dropdownAddLanguageItemName);
    }

    /**
    /* "Dropdown.NothingSelected" (Nothing is selected)
    */
    public get dropdownNothingSelected() : string {
        return this.get(this.dropdownNothingSelectedLanguageItemName);
    }

    /**
    /* "Dropdown.MultipleSelected" ({0} selected)
    */
    public get dropdownMultipleSelected() : string {
        return this.get(this.dropdownMultipleSelectedLanguageItemName);
    }

    /**
    /* "Footer.Contact" (Contact information)
    */
    public get footerContact() : string {
        return this.get(this.footerContactLanguageItemName);
    }

    /**
    /* "Footer.Frontpage" (Frontpage)
    */
    public get footerFrontpage() : string {
        return this.get(this.footerFrontpageLanguageItemName);
    }

    /**
    /* "List.Loading" (Loading...)
    */
    public get listLoading() : string {
        return this.get(this.listLoadingLanguageItemName);
    }

    /**
    /* "SignatureWidget.Clear" (Clear)
    */
    public get signatureWidgetClear() : string {
        return this.get(this.signatureWidgetClearLanguageItemName);
    }

    /**
    /* "SignatureWidget.Done" (Done)
    */
    public get signatureWidgetDone() : string {
        return this.get(this.signatureWidgetDoneLanguageItemName);
    }

    /**
    /* "Modal.SaveChanges" (Save changes)
    */
    public get modalSaveChanges() : string {
        return this.get(this.modalSaveChangesLanguageItemName);
    }

    /**
    /* "Modal.Close" (Close)
    */
    public get modalClose() : string {
        return this.get(this.modalCloseLanguageItemName);
    }

    /**
    /* "PageContainer.PageHelp" (Page help)
    */
    public get pageContainerPageHelp() : string {
        return this.get(this.pageContainerPageHelpLanguageItemName);
    }

    /**
    /* "NavigationWidget.Previous" (Previous)
    */
    public get navigationWidgetPrevious() : string {
        return this.get(this.navigationWidgetPreviousLanguageItemName);
    }

    /**
    /* "NavigationWidget.ReturnToPrevious" (Return to previous step)
    */
    public get navigationWidgetReturnToPrevious() : string {
        return this.get(this.navigationWidgetReturnToPreviousLanguageItemName);
    }

    /**
    /* "NavigationWidget.Next" (Next)
    */
    public get navigationWidgetNext() : string {
        return this.get(this.navigationWidgetNextLanguageItemName);
    }

    /**
    /* "NavigationWidget.GoToNext" (Go to next step)
    */
    public get navigationWidgetGoToNext() : string {
        return this.get(this.navigationWidgetGoToNextLanguageItemName);
    }

    /**
    /* "ConfirmationDialog.AreYouSure" (Are you sure?)
    */
    public get confirmationDialogAreYouSure() : string {
        return this.get(this.confirmationDialogAreYouSureLanguageItemName);
    }

    /**
    /* "ConfirmationDialog.ConfirmButton" (Confirm)
    */
    public get confirmationDialogConfirmButton() : string {
        return this.get(this.confirmationDialogConfirmButtonLanguageItemName);
    }

    /**
    /* "ConfirmationDialog.CloseButton" (Close)
    */
    public get confirmationDialogCloseButton() : string {
        return this.get(this.confirmationDialogCloseButtonLanguageItemName);
    }

    /**
    /* "ConfirmationDialog.Comment" (Please leave a comment)
    */
    public get confirmationDialogComment() : string {
        return this.get(this.confirmationDialogCommentLanguageItemName);
    }

    /**
    /* "Alert" ()
    */
    public get alert() : string {
        return this.get(this.alertLanguageItemName);
    }
}

//Singleton
export default new ComponentsLocalizer();