//Autogenerated

import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class NavigationWidgetLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly previousLanguageItemName: string = `Previous`;
    public readonly returnToPreviousLanguageItemName: string = `ReturnToPrevious`;
    public readonly nextLanguageItemName: string = `Next`;
    public readonly goToNextLanguageItemName: string = `GoToNext`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "da", label: "Dansk" },
                { code: "fi", label: "Suomi" },
                { code: "nb", label: "Norsk bokmål" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська" }
            ],
            "en");
        
        //Initializer
        this.set(this.previousLanguageItemName, { language: `en`, value: `Previous` }, { language: `uk`, value: `Назад` }, { language: `sv`, value: `Föregående` }, { language: `ru`, value: `Предыдущий` }, { language: `pl`, value: `Poprzedni` }, { language: `nb`, value: `Forrige` }, { language: `fi`, value: `Edellinen` }, { language: `da`, value: `Forrige` },);
        this.set(this.returnToPreviousLanguageItemName, { language: `en`, value: `Return to previous step` }, { language: `uk`, value: `Повернутися до попереднього кроку` }, { language: `sv`, value: `Återgå till föregående steg` }, { language: `ru`, value: `Вернуться на предыдущий шаг` }, { language: `pl`, value: `Powrót do poprzedniego kroku` }, { language: `nb`, value: `Gå tilbake til forrige trinn` }, { language: `fi`, value: `Palaa edelliseen vaiheeseen` }, { language: `da`, value: `Vend tilbage til forrige trin` },);
        this.set(this.nextLanguageItemName, { language: `en`, value: `Next` }, { language: `uk`, value: `Далі` }, { language: `sv`, value: `Nästa` }, { language: `ru`, value: `Далее` }, { language: `pl`, value: `Następny` }, { language: `nb`, value: `Neste` }, { language: `fi`, value: `Seuraava` }, { language: `da`, value: `Næste` },);
        this.set(this.goToNextLanguageItemName, { language: `en`, value: `Go to next step` }, { language: `uk`, value: `Перейти до наступного кроку` }, { language: `sv`, value: `Gå till nästa steg` }, { language: `ru`, value: `Перейти к следующему шагу` }, { language: `pl`, value: `Następny krok` }, { language: `nb`, value: `Gå til neste trinn` }, { language: `fi`, value: `Siirry seuraavaan vaiheeseen` }, { language: `da`, value: `Gå til næste trin` },);
    }

    /**
    /* "Previous" (Previous)
    */
    public get previous() : string {
        return this.get(this.previousLanguageItemName);
    }

    /**
    /* "ReturnToPrevious" (Return to previous step)
    */
    public get returnToPrevious() : string {
        return this.get(this.returnToPreviousLanguageItemName);
    }

    /**
    /* "Next" (Next)
    */
    public get next() : string {
        return this.get(this.nextLanguageItemName);
    }

    /**
    /* "GoToNext" (Go to next step)
    */
    public get goToNext() : string {
        return this.get(this.goToNextLanguageItemName);
    }
}

//Singleton
export default new NavigationWidgetLocalizer();