//Autogenerated

import {Language} from "@weare/reapptor-toolkit";
import {BaseComponentLocalizer} from "@weare/reapptor-react-common";

class TopNavLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly searchButtonLanguageItemName: string = `Search.Button`;

    constructor() {

        super(
            [
                new Language("en", "English"),
                new Language("da", "Dansk"),
                new Language("fi", "Suomi"),
                new Language("nb", "Norsk bokmål"),
                new Language("pl", "Polski"),
                new Language("ru", "Русский"),
                new Language("sv", "Svenska"),
                new Language("uk", "Українська")
            ],
            "en");
        
        //Initializer
        this.set(this.searchButtonLanguageItemName, { language: `en`, value: `Search` }, { language: `uk`, value: `Search` }, { language: `sv`, value: `Sök` }, { language: `ru`, value: `Search` }, { language: `pl`, value: `Szukaj` }, { language: `nb`, value: `Søg` }, { language: `fi`, value: `Etsi` }, { language: `da`, value: `Søg` },);
    }

    /**
    /* "Search.Button" (Search)
    */
    public get searchButton() : string {
        return this.get(this.searchButtonLanguageItemName);
    }
}

//Singleton
export default new TopNavLocalizer();