//Autogenerated

import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class TopNavLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly searchButtonLanguageItemName: string = `Search.Button`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "da", label: "Dansk" },
                { code: "fi", label: "Suomi" },
                { code: "nb", label: "Norsk bokmål" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська" }
            ],
            "en");
        
        //Initializer
        this.set(this.searchButtonLanguageItemName, { language: `en`, value: `Search` }, { language: `uk`, value: `Search` }, { language: `sv`, value: `Sök` }, { language: `ru`, value: `Search` }, { language: `pl`, value: `Szukaj` }, { language: `nb`, value: `Søg` }, { language: `fi`, value: `Etsi` }, { language: `da`, value: `Søg` },);
    }

    /**
    /* "Search.Button" (Search)
    */
    public get searchButton() : string {
        return this.get(this.searchButtonLanguageItemName);
    }
}

//Singleton
export default new TopNavLocalizer();