//Autogenerated

import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class AlertLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly topNavFrontpageLanguageItemName: string = `TopNav.Frontpage`;
    public readonly widgetNewSiteLabelLanguageItemName: string = `Widget.NewSite.Label`;

    constructor() {

        super(
            [
                {code: "en", label: "English"},
                {code: "fi", label: "Suomi"},
                {code: "se", label: "Svenska"},
                {code: "no", label: "Norsk bokmål"},
                {code: "da", label: "Dansk"},
                {code: "ru", label: "Русский"},
                {code: "uk", label: "Український"},
                {code: "pl", label: "Polski"},
            ],
            "en");

        //Initializer
        this.set(this.topNavFrontpageLanguageItemName, {language: `fi`, value: `Etusivu`}, {language: `sv`, value: `Framsida`}, {language: `pl`, value: `PL: Frontpage`}, {language: `en`, value: `Frontpage`},);
        this.set(this.widgetNewSiteLabelLanguageItemName, {language: `fi`, value: `Uusi työmaa`}, {language: `sv`, value: `Ny byggplats`}, {language: `pl`, value: `PL: New site`}, {language: `en`, value: `New site`},);
    }

    /**
     /* "TopNav.Frontpage" (Frontpage)
     */
    public get topNavFrontpage() : string {
        return this.get(this.topNavFrontpageLanguageItemName);
    }

    /**
     /* "Widget.NewSite.Label" (New site)
     */
    public get widgetNewSiteLabel() : string {
        return this.get(this.widgetNewSiteLabelLanguageItemName);
    }
}

//Singleton
export default new AlertLocalizer();