//Autogenerated
import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class FormLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly inputReceiverEmailLanguageItemName: string = `Input.ReceiverEmail`;
    public readonly inputPhoneLanguageItemName: string = `Input.Phone`;
    public readonly inputFirstnameLanguageItemName: string = `Input.Firstname`;
    public readonly inputMiddlenameLanguageItemName: string = `Input.Middlename`;
    public readonly inputLastnameLanguageItemName: string = `Input.Lastname`;
    public readonly inputMessageLanguageItemName: string = `Input.Message`;
    public readonly inputAddressLanguageItemName: string = `Input.Address`;
    public readonly inputStreetLanguageItemName: string = `Input.Street`;
    public readonly inputCityLanguageItemName: string = `Input.City`;
    public readonly inputPostalcodeLanguageItemName: string = `Input.Postalcode`;
    public readonly inputPostalboxLanguageItemName: string = `Input.Postalbox`;
    public readonly inputLanguageLanguageItemName: string = `Input.Language`;
    public readonly inputEmployeeNumberLanguageItemName: string = `Input.EmployeeNumber`;
    public readonly inputCostPoolLanguageItemName: string = `Input.CostPool`;
    public readonly inputWorkCardIdLanguageItemName: string = `Input.WorkCardId`;
    public readonly inputTimeTrackingDeviceIdLanguageItemName: string = `Input.TimeTrackingDeviceId`;
    public readonly inputContractSalaryHourlyPriceLanguageItemName: string = `Input.ContractSalaryHourlyPrice`;
    public readonly inputRoleLanguageItemName: string = `Input.Role`;
    public readonly inputFileDragAndDropLanguageItemName: string = `Input.File.DragAndDrop`;
    public readonly inputFileReadonlyLanguageItemName: string = `Input.File.Readonly`;
    public readonly inputFilePreviewLanguageItemName: string = `Input.File.Preview`;
    public readonly inputFileChooseFileLanguageItemName: string = `Input.File.ChooseFile`;
    public readonly inputEmailLanguageItemName: string = `Input.Email`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "fi", label: "Suomi" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" }
            ],
            "en");
        
        //Initializer
        this.set(this.inputReceiverEmailLanguageItemName, { language: `en`, value: `Receiver email` }, { language: `sv`, value: `Epost` }, { language: `ru`, value: `RU: Receiver email` }, { language: `pl`, value: `PL: Receiver email` }, { language: `fi`, value: `Vastaanottaja` },);
        this.set(this.inputPhoneLanguageItemName, { language: `en`, value: `Phone number` }, { language: `sv`, value: `Telefonnumer` }, { language: `ru`, value: `RU: Phone number` }, { language: `pl`, value: `PL: Phone number` }, { language: `fi`, value: `Puhelinnumero` },);
        this.set(this.inputFirstnameLanguageItemName, { language: `en`, value: `Firstname` }, { language: `sv`, value: `Förnamn` }, { language: `ru`, value: `RU: Firstname` }, { language: `pl`, value: `PL: Firstname` }, { language: `fi`, value: `Etunimi` },);
        this.set(this.inputMiddlenameLanguageItemName, { language: `en`, value: `Middle name` }, { language: `sv`, value: `SV: Middle name` }, { language: `ru`, value: `RU: Middle name` }, { language: `pl`, value: `PL: Middle name` }, { language: `fi`, value: `Toinen nimi` },);
        this.set(this.inputLastnameLanguageItemName, { language: `en`, value: `Lastname` }, { language: `sv`, value: `Efternamn` }, { language: `ru`, value: `RU: Lastname` }, { language: `pl`, value: `PL: Lastname` }, { language: `fi`, value: `Sukunimi` },);
        this.set(this.inputMessageLanguageItemName, { language: `en`, value: `Message` }, { language: `sv`, value: `Meddelande` }, { language: `ru`, value: `RU: Message` }, { language: `pl`, value: `PL: Message` }, { language: `fi`, value: `Viesti` },);
        this.set(this.inputAddressLanguageItemName, { language: `en`, value: `Address` }, { language: `sv`, value: `Adress` }, { language: `ru`, value: `RU: Address` }, { language: `pl`, value: `PL: Address` }, { language: `fi`, value: `Osoite` },);
        this.set(this.inputStreetLanguageItemName, { language: `en`, value: `Street` }, { language: `sv`, value: `Gata` }, { language: `ru`, value: `RU: Street` }, { language: `pl`, value: `PL: Street` }, { language: `fi`, value: `Katu` },);
        this.set(this.inputCityLanguageItemName, { language: `en`, value: `City` }, { language: `sv`, value: `Stad` }, { language: `ru`, value: `RU: City` }, { language: `pl`, value: `PL: City` }, { language: `fi`, value: `Kaupunki` },);
        this.set(this.inputPostalcodeLanguageItemName, { language: `en`, value: `Postal code` }, { language: `sv`, value: `Postnummer` }, { language: `ru`, value: `RU: Postal code` }, { language: `pl`, value: `PL: Postal code` }, { language: `fi`, value: `Postinumero` },);
        this.set(this.inputPostalboxLanguageItemName, { language: `en`, value: `Postal box` }, { language: `sv`, value: `SV: Postal box` }, { language: `ru`, value: `RU: Postal box` }, { language: `pl`, value: `PL: Postal box` }, { language: `fi`, value: `Postilaatikko` },);
        this.set(this.inputLanguageLanguageItemName, { language: `en`, value: `Language` }, { language: `sv`, value: `Språk` }, { language: `ru`, value: `RU: Language` }, { language: `pl`, value: `PL: Language` }, { language: `fi`, value: `Kieli` },);
        this.set(this.inputEmployeeNumberLanguageItemName, { language: `en`, value: `Employee number` }, { language: `sv`, value: `Användar-id` }, { language: `ru`, value: `RU: Employee number` }, { language: `pl`, value: `PL: Employee number` }, { language: `fi`, value: `Käyttäjä-id` },);
        this.set(this.inputCostPoolLanguageItemName, { language: `en`, value: `Cost pool` }, { language: `sv`, value: `Kostnadspool` }, { language: `ru`, value: `RU: Cost pool` }, { language: `pl`, value: `PL: Cost pool` }, { language: `fi`, value: `Kustannuspaikka` },);
        this.set(this.inputWorkCardIdLanguageItemName, { language: `en`, value: `Work card id` }, { language: `sv`, value: `Arbetskorts-id` }, { language: `ru`, value: `RU: Work card id` }, { language: `pl`, value: `PL: Work card id` }, { language: `fi`, value: `Valttikorti-id` },);
        this.set(this.inputTimeTrackingDeviceIdLanguageItemName, { language: `en`, value: `Time tracking device id` }, { language: `sv`, value: `SV: Time tracking device id` }, { language: `ru`, value: `RU: Time tracking device id` }, { language: `pl`, value: `PL: Time tracking device id` }, { language: `fi`, value: `Työaikaseurantalaite-id` },);
        this.set(this.inputContractSalaryHourlyPriceLanguageItemName, { language: `en`, value: `Contract salary hourly price` }, { language: `sv`, value: `Kontrakt lön timpris` }, { language: `ru`, value: `RU: Contract salary hourly price` }, { language: `pl`, value: `PL: Contract salary hourly price` }, { language: `fi`, value: `Sopimuspalkan tuntihinta` },);
        this.set(this.inputRoleLanguageItemName, { language: `en`, value: `Role` }, { language: `sv`, value: `Roll` }, { language: `ru`, value: `RU: Role` }, { language: `pl`, value: `PL: Role` }, { language: `fi`, value: `Rooli` },);
        this.set(this.inputFileDragAndDropLanguageItemName, { language: `en`, value: `Drag'n'drop file here, or click to select` }, { language: `sv`, value: `dra och släpp filen här, eller välj med att klicka` }, { language: `ru`, value: `RU: Drag'n'drop file here, or click to select` }, { language: `pl`, value: `PL: Drag'n'drop file here, or click to select` }, { language: `fi`, value: `Pudota tiedosto tähän tai valitse klikkaamalla` },);
        this.set(this.inputFileReadonlyLanguageItemName, { language: `en`, value: `File is readonly` }, { language: `sv`, value: `Filen är bara läsbar` }, { language: `ru`, value: `RU: File is readonly` }, { language: `pl`, value: `PL: File is readonly` }, { language: `fi`, value: `Tämä tiedosto on vain luettavissa` },);
        this.set(this.inputFilePreviewLanguageItemName, { language: `en`, value: `Preview` }, { language: `sv`, value: `Förhandsvisning` }, { language: `ru`, value: `RU: Preview` }, { language: `pl`, value: `PL: Preview` }, { language: `fi`, value: `Esikatselu` },);
        this.set(this.inputFileChooseFileLanguageItemName, { language: `en`, value: `Choose file` }, { language: `sv`, value: `Välj fil` }, { language: `ru`, value: `RU: Choose file` }, { language: `pl`, value: `PL: Choose file` }, { language: `fi`, value: `Valitse tiedosto` },);
        this.set(this.inputEmailLanguageItemName, { language: `en`, value: `Email` }, { language: `sv`, value: `Epost` }, { language: `ru`, value: `RU: Email` }, { language: `pl`, value: `PL: Email` }, { language: `fi`, value: `Sähköposti` },);
    }

    /**
    /* "Input.ReceiverEmail" (Receiver email)
    */
    public get inputReceiverEmail() : string {
        return this.get(this.inputReceiverEmailLanguageItemName);
    }

    /**
    /* "Input.Phone" (Phone number)
    */
    public get inputPhone() : string {
        return this.get(this.inputPhoneLanguageItemName);
    }

    /**
    /* "Input.Firstname" (Firstname)
    */
    public get inputFirstname() : string {
        return this.get(this.inputFirstnameLanguageItemName);
    }

    /**
    /* "Input.Middlename" (Middle name)
    */
    public get inputMiddlename() : string {
        return this.get(this.inputMiddlenameLanguageItemName);
    }

    /**
    /* "Input.Lastname" (Lastname)
    */
    public get inputLastname() : string {
        return this.get(this.inputLastnameLanguageItemName);
    }

    /**
    /* "Input.Message" (Message)
    */
    public get inputMessage() : string {
        return this.get(this.inputMessageLanguageItemName);
    }

    /**
    /* "Input.Address" (Address)
    */
    public get inputAddress() : string {
        return this.get(this.inputAddressLanguageItemName);
    }

    /**
    /* "Input.Street" (Street)
    */
    public get inputStreet() : string {
        return this.get(this.inputStreetLanguageItemName);
    }

    /**
    /* "Input.City" (City)
    */
    public get inputCity() : string {
        return this.get(this.inputCityLanguageItemName);
    }

    /**
    /* "Input.Postalcode" (Postal code)
    */
    public get inputPostalcode() : string {
        return this.get(this.inputPostalcodeLanguageItemName);
    }

    /**
    /* "Input.Postalbox" (Postal box)
    */
    public get inputPostalbox() : string {
        return this.get(this.inputPostalboxLanguageItemName);
    }

    /**
    /* "Input.Language" (Language)
    */
    public get inputLanguage() : string {
        return this.get(this.inputLanguageLanguageItemName);
    }

    /**
    /* "Input.EmployeeNumber" (Employee number)
    */
    public get inputEmployeeNumber() : string {
        return this.get(this.inputEmployeeNumberLanguageItemName);
    }

    /**
    /* "Input.CostPool" (Cost pool)
    */
    public get inputCostPool() : string {
        return this.get(this.inputCostPoolLanguageItemName);
    }

    /**
    /* "Input.WorkCardId" (Work card id)
    */
    public get inputWorkCardId() : string {
        return this.get(this.inputWorkCardIdLanguageItemName);
    }

    /**
    /* "Input.TimeTrackingDeviceId" (Time tracking device id)
    */
    public get inputTimeTrackingDeviceId() : string {
        return this.get(this.inputTimeTrackingDeviceIdLanguageItemName);
    }

    /**
    /* "Input.ContractSalaryHourlyPrice" (Contract salary hourly price)
    */
    public get inputContractSalaryHourlyPrice() : string {
        return this.get(this.inputContractSalaryHourlyPriceLanguageItemName);
    }

    /**
    /* "Input.Role" (Role)
    */
    public get inputRole() : string {
        return this.get(this.inputRoleLanguageItemName);
    }

    /**
    /* "Input.File.DragAndDrop" (Drag'n'drop file here, or click to select)
    */
    public get inputFileDragAndDrop() : string {
        return this.get(this.inputFileDragAndDropLanguageItemName);
    }

    /**
    /* "Input.File.Readonly" (File is readonly)
    */
    public get inputFileReadonly() : string {
        return this.get(this.inputFileReadonlyLanguageItemName);
    }

    /**
    /* "Input.File.Preview" (Preview)
    */
    public get inputFilePreview() : string {
        return this.get(this.inputFilePreviewLanguageItemName);
    }

    /**
    /* "Input.File.ChooseFile" (Choose file)
    */
    public get inputFileChooseFile() : string {
        return this.get(this.inputFileChooseFileLanguageItemName);
    }

    /**
    /* "Input.Email" (Email)
    */
    public get inputEmail() : string {
        return this.get(this.inputEmailLanguageItemName);
    }
}

//Singleton
export default new FormLocalizer();