//Autogenerated
import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class PasswordInputLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly helpTextLengthLanguageItemName: string = `HelpText.Length`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "fi", label: "Suomi" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" }
            ],
            "en");
        
        //Initializer
        this.set(this.helpTextLengthLanguageItemName, { language: `en`, value: `at least 8 characters long` }, { language: `sv`, value: `åtminstone 8 tecken` }, { language: `ru`, value: `RU: at least 8 characters long` }, { language: `pl`, value: `PL: at least 8 characters long` }, { language: `fi`, value: `vähintään 8 merkkiä` },);
    }

    /**
    /* "HelpText.Length" (at least 8 characters long)
    */
    public get helpTextLength() : string {
        return this.get(this.helpTextLengthLanguageItemName);
    }
}

//Singleton
export default new PasswordInputLocalizer();