//Autogenerated

import {BaseLocalizer} from "@weare/athenaeum-toolkit";

class Localizer extends BaseLocalizer {

    //Constants
    public readonly topNavFrontpageLanguageItemName: string = `TopNav.Frontpage`;
    public readonly pageRoutesTests2LanguageItemName: string = `PageRoutes.Tests2`;

    constructor() {

        super(
            [
                { code: "fi", label: "Suomi" },
                { code: "en", label: "English" }
            ],
            "fi");
        
        //Initializer
        this.set(this.topNavFrontpageLanguageItemName, { language: `fi`, value: `Etusivu` }, { language: `en`, value: `Frontpage` },);
        this.set(this.pageRoutesTests2LanguageItemName, { language: `fi`, value: `helloworld` }, { language: `en`, value: `hellouworld/aaa` },);
    }

    /**
    /* "TopNav.Frontpage" (Frontpage)
    */
    public get topNavFrontpage() : string {
        return this.get(this.topNavFrontpageLanguageItemName);
    }

    /**
    /* "PageRoutes.Tests2" (hellouworld/aaa)
    */
    public get pageRoutesTests2() : string {
        return this.get(this.pageRoutesTests2LanguageItemName);
    }
}

//Singleton
export default new Localizer();