//Autogenerated

import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class MessageBoxLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly okLanguageItemName: string = `Ok`;
    public readonly areYouSureLanguageItemName: string = `AreYouSure`;
    public readonly commentLanguageItemName: string = `Comment`;
    public readonly yesLanguageItemName: string = `Yes`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "da", label: "Dansk" },
                { code: "fi", label: "Suomi" },
                { code: "nb", label: "Norsk bokmål" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська" }
            ],
            "en");
        
        //Initializer
        this.set(this.okLanguageItemName, { language: `en`, value: `Ok` }, { language: `uk`, value: `Ok` }, { language: `sv`, value: `Ok` }, { language: `ru`, value: `Ok` }, { language: `pl`, value: `Ok` }, { language: `nb`, value: `Ok` }, { language: `fi`, value: `Ok` }, { language: `da`, value: `Ok` },);
        this.set(this.areYouSureLanguageItemName, { language: `en`, value: `Are you sure?` }, { language: `uk`, value: `Ви впевнені?` }, { language: `sv`, value: `Är du säker?` }, { language: `ru`, value: `Вы уверены?` }, { language: `pl`, value: `Czy jesteś pewien?` }, { language: `nb`, value: `Er du sikker?` }, { language: `fi`, value: `Oletko varma?` }, { language: `da`, value: `Er du sikker?` },);
        this.set(this.commentLanguageItemName, { language: `en`, value: `Please leave a comment` }, { language: `uk`, value: `Будьласка, залиште коментар` }, { language: `sv`, value: `Var vänlig och lämna en kommentar` }, { language: `ru`, value: `Пожалуйста, оставьте комментарий` }, { language: `pl`, value: `Dodaj komentarz` }, { language: `nb`, value: `Vennligst legg igjen en kommentar` }, { language: `fi`, value: `Ole hyvä ja kommentoi` }, { language: `da`, value: `Efterlad en kommentar` },);
        this.set(this.yesLanguageItemName, { language: `en`, value: `Yes` }, { language: `uk`, value: `UK: Yes` }, { language: `sv`, value: `SV: Yes` }, { language: `ru`, value: `Да` }, { language: `pl`, value: `PL: Yes` }, { language: `nb`, value: `NB: Yes` }, { language: `fi`, value: `FI: Yes` }, { language: `da`, value: `DA: Yes` },);
    }

    /**
    /* "Ok" (Ok)
    */
    public get ok() : string {
        return this.get(this.okLanguageItemName);
    }

    /**
    /* "AreYouSure" (Are you sure?)
    */
    public get areYouSure() : string {
        return this.get(this.areYouSureLanguageItemName);
    }

    /**
    /* "Comment" (Please leave a comment)
    */
    public get comment() : string {
        return this.get(this.commentLanguageItemName);
    }

    /**
    /* "Yes" (Yes)
    */
    public get yes() : string {
        return this.get(this.yesLanguageItemName);
    }
}

//Singleton
export default new MessageBoxLocalizer();