//Autogenerated

import {Language} from "@weare/reapptor-toolkit";
import {BaseComponentLocalizer} from "@weare/reapptor-react-common";

class AddressInputLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly validatorsCustomRequiredLanguageItemName: string = `Validators.Custom.Required`;

    constructor() {

        super(
            [
                new Language("en", "English"),
                new Language("da", "Dansk"),
                new Language("fi", "Suomi"),
                new Language("nb", "Norsk bokmål"),
                new Language("pl", "Polski"),
                new Language("ru", "Русский"),
                new Language("sv", "Svenska"),
                new Language("uk", "Українська")
            ],
            "en");
        
        //Initializer
        this.set(this.validatorsCustomRequiredLanguageItemName, { language: `en`, value: `Type and select an address from the list` }, { language: `sv`, value: `Skriv och välj en adress i listan` }, { language: `pl`, value: `Wpisz i wybierz adres z listy` }, { language: `nb`, value: `Skriv inn og velg en adresse fra listen` }, { language: `fi`, value: `Kirjoita ja valitse osoite listasta` }, { language: `da`, value: `Skriv og vælg en adresse på listen` },);
    }

    /**
    /* "Validators.Custom.Required" (Type and select an address from the list)
    */
    public get validatorsCustomRequired() : string {
        return this.get(this.validatorsCustomRequiredLanguageItemName);
    }
}

//Singleton
export default new AddressInputLocalizer();