//Autogenerated

import {Language} from "@weare/reapptor-toolkit";
import {BaseComponentLocalizer} from "@weare/reapptor-react-common";

class LocationPickerModalLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly titleLanguageItemName: string = `Title`;
    public readonly subtitleLanguageItemName: string = `Subtitle`;
    public readonly setLocationLanguageItemName: string = `SetLocation`;

    constructor() {

        super(
            [
                new Language("en", "English"),
                new Language("da", "Dansk"),
                new Language("fi", "Suomi"),
                new Language("nb", "Norsk bokmål"),
                new Language("pl", "Polski"),
                new Language("ru", "Русский"),
                new Language("sv", "Svenska"),
                new Language("uk", "Українська")
            ],
            "en");
        
        //Initializer
        this.set(this.titleLanguageItemName, { language: `en`, value: `Location picker` }, { language: `uk`, value: `Вибір розташування` }, { language: `sv`, value: `Platsväljare` }, { language: `ru`, value: `Выбор местоположения` }, { language: `pl`, value: `Wybierz lokalizację` }, { language: `nb`, value: `Stedsvelger` }, { language: `fi`, value: `Sijaintivalitsin` }, { language: `da`, value: `Placeringsvælger` },);
        this.set(this.subtitleLanguageItemName, { language: `en`, value: `Choose location on map` }, { language: `uk`, value: `Оберіть місце на мапі` }, { language: `sv`, value: `Välj plats på kartan` }, { language: `ru`, value: `Выбрать местоположение на карте` }, { language: `pl`, value: `Wybierz lokalizację na mapie` }, { language: `nb`, value: `Velg plassering på kartet` }, { language: `fi`, value: `Valitse sijainti kartalla` }, { language: `da`, value: `Vælg placering på kortet` },);
        this.set(this.setLocationLanguageItemName, { language: `en`, value: `Set location` }, { language: `uk`, value: `Оберіть адресу` }, { language: `sv`, value: `Ställ in plats` }, { language: `ru`, value: `Установить местоположение` }, { language: `pl`, value: `Ustaw lokalizację` }, { language: `nb`, value: `Angi sted` }, { language: `fi`, value: `Aseta sijainti` }, { language: `da`, value: `Indstil placering` },);
    }

    /**
    /* "Title" (Location picker)
    */
    public get title() : string {
        return this.get(this.titleLanguageItemName);
    }

    /**
    /* "Subtitle" (Choose location on map)
    */
    public get subtitle() : string {
        return this.get(this.subtitleLanguageItemName);
    }

    /**
    /* "SetLocation" (Set location)
    */
    public get setLocation() : string {
        return this.get(this.setLocationLanguageItemName);
    }
}

//Singleton
export default new LocationPickerModalLocalizer();