//Autogenerated

import {BaseComponentLocalizer} from "@weare/reapptor-react-common";

class PageContainerLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly pageHelpLanguageItemName: string = `PageHelp`;

    constructor() {

        super(
            [
                { code: "en", label: "English", isLanguage: true },
                { code: "da", label: "Dansk", isLanguage: true },
                { code: "fi", label: "Suomi", isLanguage: true },
                { code: "nb", label: "Norsk bokmål", isLanguage: true },
                { code: "pl", label: "Polski", isLanguage: true },
                { code: "ru", label: "Русский", isLanguage: true },
                { code: "sv", label: "Svenska", isLanguage: true },
                { code: "uk", label: "Українська", isLanguage: true }
            ],
            "en");
        
        //Initializer
        this.set(this.pageHelpLanguageItemName, { language: `en`, value: `Page help` }, { language: `uk`, value: `Довідка` }, { language: `sv`, value: `Sidhjälp` }, { language: `ru`, value: `Справка` }, { language: `pl`, value: `Pomoc strony` }, { language: `nb`, value: `Sidehjelp` }, { language: `fi`, value: `Sivun ohje` }, { language: `da`, value: `Hjælp til sider` },);
    }

    /**
    /* "PageHelp" (Page help)
    */
    public get pageHelp() : string {
        return this.get(this.pageHelpLanguageItemName);
    }
}

//Singleton
export default new PageContainerLocalizer();