//Autogenerated

import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class LayoutLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly fourColumnsLanguageItemName: string = `FourColumns`;
    public readonly oneColumnLanguageItemName: string = `OneColumn`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "fi", label: "Suomi" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська" }
            ],
            "en");
        
        //Initializer
        this.set(this.fourColumnsLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` },);
        this.set(this.oneColumnLanguageItemName, { language: `en`, value: `` }, { language: `uk`, value: `` },);
    }

    /**
    /* "FourColumns" ()
    */
    public get fourColumns() : string {
        return this.get(this.fourColumnsLanguageItemName);
    }

    /**
    /* "OneColumn" ()
    */
    public get oneColumn() : string {
        return this.get(this.oneColumnLanguageItemName);
    }
}

//Singleton
export default new LayoutLocalizer();