//Autogenerated

import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class PasswordFormLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly helpTextUpperCaseLanguageItemName: string = `HelpText.UpperCase`;
    public readonly helpTextLowerCaseLanguageItemName: string = `HelpText.LowerCase`;
    public readonly helpTextNumberLanguageItemName: string = `HelpText.Number`;
    public readonly helpTextSpecialCharacterLanguageItemName: string = `HelpText.SpecialCharacter`;
    public readonly resetPasswordPasswordsDontMatchMessageLanguageItemName: string = `ResetPassword.PasswordsDontMatchMessage`;
    public readonly changePasswordCurrentPasswordLanguageItemName: string = `ChangePassword.CurrentPassword`;
    public readonly loginPagePasswordInputLanguageItemName: string = `LoginPage.PasswordInput`;
    public readonly resetPasswordConfirmPasswordInputLanguageItemName: string = `ResetPassword.ConfirmPasswordInput`;
    public readonly saveLanguageItemName: string = `Save`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "da", label: "Dansk" },
                { code: "fi", label: "Suomi" },
                { code: "nb", label: "Norsk bokmål" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська" }
            ],
            "en");
        
        //Initializer
        this.set(this.helpTextUpperCaseLanguageItemName, { language: `en`, value: `one uppercase ('A'-'Z') character` }, { language: `uk`, value: `одна велика літера ('A'-'Z')` }, { language: `sv`, value: `en stor bokstav ('A'-'Z')` }, { language: `ru`, value: `одна прописная буква ('A'-'Z')` }, { language: `pl`, value: `jedną dużą literę (A-Z)` }, { language: `nb`, value: `En stor bokstav ('A' - 'Z')` }, { language: `fi`, value: `yksi iso kirjain ('A'-'Z')` }, { language: `da`, value: `Et stort ('A' - 'Z') tegn` },);
        this.set(this.helpTextLowerCaseLanguageItemName, { language: `en`, value: `one lowercase ('a'-'z') character` }, { language: `uk`, value: `одна мала буква ('a'-'z')` }, { language: `sv`, value: `en liten bokstav ('a'-'z')` }, { language: `ru`, value: `одна строчная буква ('a'-'z')` }, { language: `pl`, value: `jedną małą literę (a-z)` }, { language: `nb`, value: `En liten bokstav ('a' - 'z')` }, { language: `fi`, value: `yksi pieni kirjain ('a'-'z')` }, { language: `da`, value: `En lille bogstav ('a' - 'z')` },);
        this.set(this.helpTextNumberLanguageItemName, { language: `en`, value: `one number` }, { language: `uk`, value: `одна цифра` }, { language: `sv`, value: `en nummer` }, { language: `ru`, value: `одна цифра` }, { language: `pl`, value: `jedną cyfrę` }, { language: `nb`, value: `Ett nummer` }, { language: `fi`, value: `yksi numero` }, { language: `da`, value: `Et nummer` },);
        this.set(this.helpTextSpecialCharacterLanguageItemName, { language: `en`, value: `one special character` }, { language: `uk`, value: `один буквено-цифровий символ` }, { language: `sv`, value: `ett special tecken` }, { language: `ru`, value: `один  буквенно-цифровой символ` }, { language: `pl`, value: `jeden znak specjalny` }, { language: `nb`, value: `En spesiell karakter` }, { language: `fi`, value: `yksi erikoismerkki` }, { language: `da`, value: `En speciel karakter` },);
        this.set(this.resetPasswordPasswordsDontMatchMessageLanguageItemName, { language: `en`, value: `Passwords don't match` }, { language: `uk`, value: `Паролі не співпадають` }, { language: `sv`, value: `Lösenorden matchar inte` }, { language: `ru`, value: `Пароли не совпадают` }, { language: `pl`, value: `Hasła niejednakowe` }, { language: `nb`, value: `Passord er ulike` }, { language: `fi`, value: `Salasanat eivät täsmää` }, { language: `da`, value: `Adgangskoderne matcher ikke` },);
        this.set(this.changePasswordCurrentPasswordLanguageItemName, { language: `en`, value: `Current password` }, { language: `uk`, value: `Поточний пароль` }, { language: `sv`, value: `Nuvarande lösenord` }, { language: `ru`, value: `Текущий пароль` }, { language: `pl`, value: `Aktualne hasło` }, { language: `nb`, value: `Nåverende passord` }, { language: `fi`, value: `Nykyinen salasana` }, { language: `da`, value: `Nuværende adgangskode` },);
        this.set(this.loginPagePasswordInputLanguageItemName, { language: `en`, value: `Password` }, { language: `uk`, value: `Пароль` }, { language: `sv`, value: `Lösenord` }, { language: `ru`, value: `Пароль` }, { language: `pl`, value: `Hasło` }, { language: `nb`, value: `Passord` }, { language: `fi`, value: `Salasana` }, { language: `da`, value: `Adgangskode` },);
        this.set(this.resetPasswordConfirmPasswordInputLanguageItemName, { language: `en`, value: `Confirm password` }, { language: `uk`, value: `Підтвердити пароль` }, { language: `sv`, value: `Bekräfta lösenord` }, { language: `ru`, value: `Подтвердить пароль` }, { language: `pl`, value: `Potwiedż hasło` }, { language: `nb`, value: `Bekreft passord` }, { language: `fi`, value: `Vahvista salasana` }, { language: `da`, value: `Bekræft adgangskode` },);
        this.set(this.saveLanguageItemName, { language: `en`, value: `Save` }, { language: `uk`, value: `Зберегти` }, { language: `sv`, value: `Spara` }, { language: `ru`, value: `Сохранить` }, { language: `pl`, value: `Zapisz` }, { language: `nb`, value: `Lagre` }, { language: `fi`, value: `Tallenna` }, { language: `da`, value: `Gem` },);
    }

    /**
    /* "HelpText.UpperCase" (one uppercase ('A'-'Z') character)
    */
    public get helpTextUpperCase() : string {
        return this.get(this.helpTextUpperCaseLanguageItemName);
    }

    /**
    /* "HelpText.LowerCase" (one lowercase ('a'-'z') character)
    */
    public get helpTextLowerCase() : string {
        return this.get(this.helpTextLowerCaseLanguageItemName);
    }

    /**
    /* "HelpText.Number" (one number)
    */
    public get helpTextNumber() : string {
        return this.get(this.helpTextNumberLanguageItemName);
    }

    /**
    /* "HelpText.SpecialCharacter" (one special character)
    */
    public get helpTextSpecialCharacter() : string {
        return this.get(this.helpTextSpecialCharacterLanguageItemName);
    }

    /**
    /* "ResetPassword.PasswordsDontMatchMessage" (Passwords don't match)
    */
    public get resetPasswordPasswordsDontMatchMessage() : string {
        return this.get(this.resetPasswordPasswordsDontMatchMessageLanguageItemName);
    }

    /**
    /* "ChangePassword.CurrentPassword" (Current password)
    */
    public get changePasswordCurrentPassword() : string {
        return this.get(this.changePasswordCurrentPasswordLanguageItemName);
    }

    /**
    /* "LoginPage.PasswordInput" (Password)
    */
    public get loginPagePasswordInput() : string {
        return this.get(this.loginPagePasswordInputLanguageItemName);
    }

    /**
    /* "ResetPassword.ConfirmPasswordInput" (Confirm password)
    */
    public get resetPasswordConfirmPasswordInput() : string {
        return this.get(this.resetPasswordConfirmPasswordInputLanguageItemName);
    }

    /**
    /* "Save" (Save)
    */
    public get save() : string {
        return this.get(this.saveLanguageItemName);
    }
}

//Singleton
export default new PasswordFormLocalizer();