//Autogenerated

import {Language} from "@weare/reapptor-toolkit";
import {BaseComponentLocalizer} from "@weare/reapptor-react-common";

class AddressDividerLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly addressLanguageItemName: string = `Address`;
    public readonly streetLanguageItemName: string = `Street`;
    public readonly cityLanguageItemName: string = `City`;
    public readonly postalCodeLanguageItemName: string = `PostalCode`;

    constructor() {

        super(
            [
                new Language("en", "English"),
                new Language("da", "Dansk"),
                new Language("fi", "Suomi"),
                new Language("nb", "Norsk bokmål"),
                new Language("pl", "Polski"),
                new Language("ru", "Русский"),
                new Language("sv", "Svenska"),
                new Language("uk", "Українська")
            ],
            "en");
        
        //Initializer
        this.set(this.addressLanguageItemName, { language: `en`, value: `Address` }, { language: `uk`, value: `Адреса` }, { language: `sv`, value: `Adress` }, { language: `ru`, value: `Адрес` }, { language: `pl`, value: `Adres` }, { language: `nb`, value: `Addresse` }, { language: `fi`, value: `Osoite` }, { language: `da`, value: `Adresse` },);
        this.set(this.streetLanguageItemName, { language: `en`, value: `Street` }, { language: `uk`, value: `Вулиця` }, { language: `sv`, value: `Gata` }, { language: `ru`, value: `Улица` }, { language: `pl`, value: `Ulica` }, { language: `nb`, value: `Gate` }, { language: `fi`, value: `Katu` }, { language: `da`, value: `Gade` },);
        this.set(this.cityLanguageItemName, { language: `en`, value: `City` }, { language: `uk`, value: `Місто` }, { language: `sv`, value: `Stad` }, { language: `ru`, value: `Город` }, { language: `pl`, value: `Miasto` }, { language: `nb`, value: `By` }, { language: `fi`, value: `Kaupunki` }, { language: `da`, value: `By` },);
        this.set(this.postalCodeLanguageItemName, { language: `en`, value: `Postal code` }, { language: `uk`, value: `Поштовий індекс` }, { language: `sv`, value: `Postnummer` }, { language: `ru`, value: `Почтовый индекс` }, { language: `pl`, value: `Kod pocztowy` }, { language: `nb`, value: `Postnummer` }, { language: `fi`, value: `Postinumero` }, { language: `da`, value: `Postnummer` },);
    }

    /**
    /* "Address" (Address)
    */
    public get address() : string {
        return this.get(this.addressLanguageItemName);
    }

    /**
    /* "Street" (Street)
    */
    public get street() : string {
        return this.get(this.streetLanguageItemName);
    }

    /**
    /* "City" (City)
    */
    public get city() : string {
        return this.get(this.cityLanguageItemName);
    }

    /**
    /* "PostalCode" (Postal code)
    */
    public get postalCode() : string {
        return this.get(this.postalCodeLanguageItemName);
    }
}

//Singleton
export default new AddressDividerLocalizer();