//Autogenerated

import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class AddressDividerLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly addressLanguageItemName: string = `Address`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "da", label: "Dansk" },
                { code: "fi", label: "Suomi" },
                { code: "nb", label: "Norsk bokmål" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська" }
            ],
            "en");
        
        //Initializer
        this.set(this.addressLanguageItemName, { language: `en`, value: `Address` }, { language: `uk`, value: `UK: Address` }, { language: `sv`, value: `Adress` }, { language: `ru`, value: `RU: Address` }, { language: `pl`, value: `PL: Address` }, { language: `nb`, value: `Address` }, { language: `fi`, value: `Osoite` }, { language: `da`, value: `Address` },);
    }

    /**
    /* "Address" (Address)
    */
    public get address() : string {
        return this.get(this.addressLanguageItemName);
    }
}

//Singleton
export default new AddressDividerLocalizer();