//Autogenerated

import {Language} from "@weare/reapptor-toolkit";
import {BaseComponentLocalizer} from "@weare/reapptor-react-common";

class FooterLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly frontpageLanguageItemName: string = `Frontpage`;
    public readonly contactLanguageItemName: string = `Contact`;

    constructor() {

        super(
            [
                new Language("en", "English"),
                new Language("da", "Dansk"),
                new Language("fi", "Suomi"),
                new Language("nb", "Norsk bokmål"),
                new Language("pl", "Polski"),
                new Language("ru", "Русский"),
                new Language("sv", "Svenska"),
                new Language("uk", "Українська")
            ],
            "en");
        
        //Initializer
        this.set(this.frontpageLanguageItemName, { language: `en`, value: `Frontpage` }, { language: `uk`, value: `Головна сторінка` }, { language: `sv`, value: `Framsida` }, { language: `ru`, value: `Главная страница` }, { language: `pl`, value: `Strona główna` }, { language: `nb`, value: `Hjemmeside` }, { language: `fi`, value: `Etusivu` }, { language: `da`, value: `Forside` },);
        this.set(this.contactLanguageItemName, { language: `en`, value: `Contact information` }, { language: `uk`, value: `Контактна інформація` }, { language: `sv`, value: `Kontakt information` }, { language: `ru`, value: `Контактная информация` }, { language: `pl`, value: `Informacje kontaktowe` }, { language: `nb`, value: `Kontakt informasjon` }, { language: `fi`, value: `Yhteystiedot` }, { language: `da`, value: `Kontaktinformation` },);
    }

    /**
    /* "Frontpage" (Frontpage)
    */
    public get frontpage() : string {
        return this.get(this.frontpageLanguageItemName);
    }

    /**
    /* "Contact" (Contact information)
    */
    public get contact() : string {
        return this.get(this.contactLanguageItemName);
    }
}

//Singleton
export default new FooterLocalizer();