//Autogenerated

using System.Collections.ObjectModel;
using System.Globalization;

namespace Renta.TestApplication.WebUI.Resources
{
    public static class SharedResources
    {
        public static readonly ReadOnlyCollection<CultureInfo> SupportedCultures = new ReadOnlyCollection<CultureInfo>(new[]
        {
            new CultureInfo("fi"),
            new CultureInfo("en"),
        });

        public static readonly CultureInfo DefaultCulture = new CultureInfo("fi");

        /// <summary>
        /// "TopNav.Frontpage" (Frontpage)
        /// </summary>
        public const string TopNavFrontpage = @"TopNav.Frontpage";

        /// <summary>
        /// "PageRoutes.Tests2" (hellouworld/aaa)
        /// </summary>
        public const string PageRoutesTests2 = @"PageRoutes.Tests2";

        /// <summary>
        /// "DayOfWeek.Monday" (Monday)
        /// </summary>
        public const string DayOfWeekMonday = @"DayOfWeek.Monday";

        /// <summary>
        /// "DayOfWeek.Tuesday" (Tuesday)
        /// </summary>
        public const string DayOfWeekTuesday = @"DayOfWeek.Tuesday";

        /// <summary>
        /// "DayOfWeek.Wednsday" (Wednsday)
        /// </summary>
        public const string DayOfWeekWednsday = @"DayOfWeek.Wednsday";

        /// <summary>
        /// "DayOfWeek.Thursday" (Thursday)
        /// </summary>
        public const string DayOfWeekThursday = @"DayOfWeek.Thursday";

        /// <summary>
        /// "DayOfWeek.Friday" (Friday)
        /// </summary>
        public const string DayOfWeekFriday = @"DayOfWeek.Friday";

        /// <summary>
        /// "DayOfWeek.Saturday" (Saturday)
        /// </summary>
        public const string DayOfWeekSaturday = @"DayOfWeek.Saturday";

        /// <summary>
        /// "DayOfWeek.Sunday" (Sunday)
        /// </summary>
        public const string DayOfWeekSunday = @"DayOfWeek.Sunday";

        /// <summary>
        /// "PageRoutes.AnonymousTestWithParameters" (aaa)
        /// </summary>
        public const string PageRoutesAnonymousTestWithParameters = @"PageRoutes.AnonymousTestWithParameters";
    }
}
