//Autogenerated

using System.Collections.ObjectModel;
using System.Globalization;

namespace Renta.TestApplication.WebUI.Resources
{
    public static class SharedResources
    {
        public static readonly ReadOnlyCollection<CultureInfo> SupportedCultures = new ReadOnlyCollection<CultureInfo>(new[]
        {
            new CultureInfo("fi"),
            new CultureInfo("en"),
        });

        public static readonly CultureInfo DefaultCulture = new CultureInfo("fi");

        /// <summary>
        /// "TopNav.Frontpage" (Frontpage)
        /// </summary>
        public const string TopNavFrontpage = @"TopNav.Frontpage";

        /// <summary>
        /// "PageRoutes.Tests2" (hellouworld/aaa)
        /// </summary>
        public const string PageRoutesTests2 = @"PageRoutes.Tests2";
    }
}
