//Autogenerated

import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class ImageModalLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly previewNotSupportedLanguageItemName: string = `PreviewNotSupported`;
    public readonly downloadLanguageItemName: string = `Download`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "da", label: "Dansk" },
                { code: "fi", label: "Suomi" },
                { code: "nb", label: "Norsk bokmål" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська" }
            ],
            "en");
        
        //Initializer
        this.set(this.previewNotSupportedLanguageItemName, { language: `en`, value: `Preview is not supported for this type of file, but you can download it instead` }, { language: `uk`, value: `UK: Preview is not supported for this type of file, but you can download it instead` }, { language: `sv`, value: `SV: Preview is not supported for this type of file, but you can download it instead` }, { language: `ru`, value: `RU: Preview is not supported for this type of file, but you can download it instead` }, { language: `pl`, value: `Podgląd dokumentu niemożliwy` }, { language: `nb`, value: `NB: Preview is not supported for this type of file, but you can download it instead` }, { language: `fi`, value: `Tiedosto ei tue esikatselua. Voit ladata tiedoston katselua varten` }, { language: `da`, value: `DA: Preview is not supported for this type of file, but you can download it instead` },);
        this.set(this.downloadLanguageItemName, { language: `en`, value: `Download` }, { language: `uk`, value: `Завантажити` }, { language: `sv`, value: `SV: Download` }, { language: `ru`, value: `Загрузить` }, { language: `pl`, value: `PL: Download` }, { language: `nb`, value: `NB: Download` }, { language: `fi`, value: `Lataa` }, { language: `da`, value: `DA: Download` },);
    }

    /**
    /* "PreviewNotSupported" (Preview is not supported for this type of file, but you can download it instead)
    */
    public get previewNotSupported() : string {
        return this.get(this.previewNotSupportedLanguageItemName);
    }

    /**
    /* "Download" (Download)
    */
    public get download() : string {
        return this.get(this.downloadLanguageItemName);
    }
}

//Singleton
export default new ImageModalLocalizer();