//Autogenerated

import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class ModalLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly saveChangesLanguageItemName: string = `SaveChanges`;
    public readonly closeLanguageItemName: string = `Close`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "da", label: "Dansk" },
                { code: "fi", label: "Suomi" },
                { code: "nb", label: "Norsk bokmål" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська" }
            ],
            "en");
        
        //Initializer
        this.set(this.saveChangesLanguageItemName, { language: `en`, value: `Save changes` }, { language: `uk`, value: `UK: Save changes` }, { language: `sv`, value: `Spara ändringar` }, { language: `ru`, value: `Созранить изменения` }, { language: `pl`, value: `PL: Save changes` }, { language: `nb`, value: `Save changes` }, { language: `fi`, value: `Tallenna muutokset` }, { language: `da`, value: `Save changes` },);
        this.set(this.closeLanguageItemName, { language: `en`, value: `Close` }, { language: `uk`, value: `UK: Close` }, { language: `sv`, value: `Stäng` }, { language: `ru`, value: `Закрыть` }, { language: `pl`, value: `PL: Close` }, { language: `nb`, value: `Close` }, { language: `fi`, value: `Sulje` }, { language: `da`, value: `Close` },);
    }

    /**
    /* "SaveChanges" (Save changes)
    */
    public get saveChanges() : string {
        return this.get(this.saveChangesLanguageItemName);
    }

    /**
    /* "Close" (Close)
    */
    public get close() : string {
        return this.get(this.closeLanguageItemName);
    }
}

//Singleton
export default new ModalLocalizer();