//Autogenerated
import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class BarWidgetLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly budgetDataModuleLabelLanguageItemName: string = `BudgetData.Module.Label`;
    public readonly budgetDataPerimeterFrameLabelLanguageItemName: string = `BudgetData.PerimeterFrame.Label`;
    public readonly budgetDataWeatherShelterLabelLanguageItemName: string = `BudgetData.WeatherShelter.Label`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "fi", label: "Suomi" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" }
            ],
            "en");
        
        //Initializer
        this.set(this.budgetDataModuleLabelLanguageItemName, { language: `en`, value: `Module` }, { language: `sv`, value: `SV: Module` }, { language: `ru`, value: `RU: Module` }, { language: `pl`, value: `PL: Module` }, { language: `fi`, value: `Moduuli` },);
        this.set(this.budgetDataPerimeterFrameLabelLanguageItemName, { language: `en`, value: `Perimeter frame` }, { language: `sv`, value: `SV: Perimeter frame` }, { language: `ru`, value: `RU: Perimeter frame` }, { language: `pl`, value: `PL: Perimeter frame` }, { language: `fi`, value: `Kehäteline` },);
        this.set(this.budgetDataWeatherShelterLabelLanguageItemName, { language: `en`, value: `Weather shelter` }, { language: `sv`, value: `SV: Weather shelter` }, { language: `ru`, value: `RU: Weather shelter` }, { language: `pl`, value: `PL: Weather shelter` }, { language: `fi`, value: `Sääsuoja` },);
    }

    /**
    /* "BudgetData.Module.Label" (Module)
    */
    public get budgetDataModuleLabel() : string {
        return this.get(this.budgetDataModuleLabelLanguageItemName);
    }

    /**
    /* "BudgetData.PerimeterFrame.Label" (Perimeter frame)
    */
    public get budgetDataPerimeterFrameLabel() : string {
        return this.get(this.budgetDataPerimeterFrameLabelLanguageItemName);
    }

    /**
    /* "BudgetData.WeatherShelter.Label" (Weather shelter)
    */
    public get budgetDataWeatherShelterLabel() : string {
        return this.get(this.budgetDataWeatherShelterLabelLanguageItemName);
    }
}

//Singleton
export default new BarWidgetLocalizer();