//Autogenerated

import {Language} from "@weare/reapptor-toolkit";
import {BaseComponentLocalizer} from "@weare/reapptor-react-common";

class ModalLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly saveChangesLanguageItemName: string = `SaveChanges`;
    public readonly closeLanguageItemName: string = `Close`;

    constructor() {

        super(
            [
                new Language("en", "English"),
                new Language("da", "Dansk"),
                new Language("fi", "Suomi"),
                new Language("nb", "Norsk bokmål"),
                new Language("pl", "Polski"),
                new Language("ru", "Русский"),
                new Language("sv", "Svenska"),
                new Language("uk", "Українська")
            ],
            "en");
        
        //Initializer
        this.set(this.saveChangesLanguageItemName, { language: `en`, value: `Save changes` }, { language: `uk`, value: `Зберегти зміни` }, { language: `sv`, value: `Spara ändringar` }, { language: `ru`, value: `Сохранить изменения` }, { language: `pl`, value: `Zachowaj zmiany` }, { language: `nb`, value: `Lagre endringer` }, { language: `fi`, value: `Tallenna muutokset` }, { language: `da`, value: `Gem ændringer` },);
        this.set(this.closeLanguageItemName, { language: `en`, value: `Close` }, { language: `uk`, value: `Закрити` }, { language: `sv`, value: `Stäng` }, { language: `ru`, value: `Закрыть` }, { language: `pl`, value: `Zamknij` }, { language: `nb`, value: `Lukke` }, { language: `fi`, value: `Sulje` }, { language: `da`, value: `Luk` },);
    }

    /**
    /* "SaveChanges" (Save changes)
    */
    public get saveChanges() : string {
        return this.get(this.saveChangesLanguageItemName);
    }

    /**
    /* "Close" (Close)
    */
    public get close() : string {
        return this.get(this.closeLanguageItemName);
    }
}

//Singleton
export default new ModalLocalizer();