//Autogenerated

import {Language} from "@weare/reapptor-toolkit";
import {BaseComponentLocalizer} from "@weare/reapptor-react-common";

class FileInputLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly dragAndDropLanguageItemName: string = `DragAndDrop`;
    public readonly readonlyLanguageItemName: string = `Readonly`;
    public readonly chooseFileLanguageItemName: string = `ChooseFile`;
    public readonly previewLanguageItemName: string = `Preview`;

    constructor() {

        super(
            [
                new Language("en", "English"),
                new Language("da", "Dansk"),
                new Language("fi", "Suomi"),
                new Language("nb", "Norsk bokmål"),
                new Language("pl", "Polski"),
                new Language("ru", "Русский"),
                new Language("sv", "Svenska"),
                new Language("uk", "Українська")
            ],
            "en");
        
        //Initializer
        this.set(this.dragAndDropLanguageItemName, { language: `en`, value: `Drag'n'drop file here, or click to select` }, { language: `uk`, value: `Перетягніть файл, або оберіть його` }, { language: `sv`, value: `Släpp filen här eller välj genom att trycka` }, { language: `ru`, value: `Перетащите файл сюда или щелкните, чтобы выбрать` }, { language: `pl`, value: `Przeciągnij pliki tutaj i upuść albo kliknij aby wybrać` }, { language: `nb`, value: `Dra og drop filen hit, eller klikk for å velge` }, { language: `fi`, value: `Pudota tiedosto tähän tai valitse klikkaamalla` }, { language: `da`, value: `Placer filen her, eller vælg ved at klikke` },);
        this.set(this.readonlyLanguageItemName, { language: `en`, value: `File is readonly` }, { language: `uk`, value: `Файл доступний лише для читання` }, { language: `sv`, value: `Filen är bara läsbar` }, { language: `ru`, value: `Файл доступен только для чтения` }, { language: `pl`, value: `Plik tylko do odczytu` }, { language: `nb`, value: `Filen er skrivebeskyttet` }, { language: `fi`, value: `Tämä tiedosto on vain luettavissa` }, { language: `da`, value: `Fil er readonly` },);
        this.set(this.chooseFileLanguageItemName, { language: `en`, value: `Choose file` }, { language: `uk`, value: `Оберіть файл` }, { language: `sv`, value: `Välj fil` }, { language: `ru`, value: `Выберите файл` }, { language: `pl`, value: `Wybierz plik` }, { language: `nb`, value: `Velg fil` }, { language: `fi`, value: `Valitse tiedosto` }, { language: `da`, value: `Vælg fil` },);
        this.set(this.previewLanguageItemName, { language: `en`, value: `Preview` }, { language: `uk`, value: `Переглянути` }, { language: `sv`, value: `Förhandsvisning` }, { language: `ru`, value: `Предпросмотр` }, { language: `pl`, value: `Podgląd` }, { language: `nb`, value: `Forhåndsvisning` }, { language: `fi`, value: `Esikatselu` }, { language: `da`, value: `Eksempel` },);
    }

    /**
    /* "DragAndDrop" (Drag'n'drop file here, or click to select)
    */
    public get dragAndDrop() : string {
        return this.get(this.dragAndDropLanguageItemName);
    }

    /**
    /* "Readonly" (File is readonly)
    */
    public get readonly() : string {
        return this.get(this.readonlyLanguageItemName);
    }

    /**
    /* "ChooseFile" (Choose file)
    */
    public get chooseFile() : string {
        return this.get(this.chooseFileLanguageItemName);
    }

    /**
    /* "Preview" (Preview)
    */
    public get preview() : string {
        return this.get(this.previewLanguageItemName);
    }
}

//Singleton
export default new FileInputLocalizer();