//Autogenerated

import {Language} from "@weare/reapptor-toolkit";
import {BaseComponentLocalizer} from "@weare/reapptor-react-common";

class ImageModalLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly previewNotSupportedLanguageItemName: string = `PreviewNotSupported`;
    public readonly downloadLanguageItemName: string = `Download`;

    constructor() {

        super(
            [
                new Language("en", "English"),
                new Language("da", "Dansk"),
                new Language("fi", "Suomi"),
                new Language("nb", "Norsk bokmål"),
                new Language("pl", "Polski"),
                new Language("ru", "Русский"),
                new Language("sv", "Svenska"),
                new Language("uk", "Українська")
            ],
            "en");
        
        //Initializer
        this.set(this.previewNotSupportedLanguageItemName, { language: `en`, value: `Preview is not supported for this type of file, but you can download it instead` }, { language: `uk`, value: `Попередній перегляд не підтримується для файлів цього типу, але ви можете завантажити його замість цього.` }, { language: `sv`, value: `Förhandsgranskning stöds inte för denna typ av fil, men du kan ladda ner den istället` }, { language: `ru`, value: `Предварительный просмотр не поддерживается для файлов этого типа, но вы можете скачать его вместо этого.` }, { language: `pl`, value: `Podgląd dokumentu niemożliwy` }, { language: `nb`, value: `Forhåndsvisning støttes ikke for denne typen filer, men du kan laste den ned i stedet` }, { language: `fi`, value: `Tiedosto ei tue esikatselua. Voit ladata tiedoston katselua varten` }, { language: `da`, value: `Preview understøttes ikke for denne type fil, men du kan downloade den i stedet` },);
        this.set(this.downloadLanguageItemName, { language: `en`, value: `Download` }, { language: `uk`, value: `Завантажити` }, { language: `sv`, value: `Ladda ner` }, { language: `ru`, value: `Загрузить` }, { language: `pl`, value: `Pobierz` }, { language: `nb`, value: `Last ned` }, { language: `fi`, value: `Lataa` }, { language: `da`, value: `Download` },);
    }

    /**
    /* "PreviewNotSupported" (Preview is not supported for this type of file, but you can download it instead)
    */
    public get previewNotSupported() : string {
        return this.get(this.previewNotSupportedLanguageItemName);
    }

    /**
    /* "Download" (Download)
    */
    public get download() : string {
        return this.get(this.downloadLanguageItemName);
    }
}

//Singleton
export default new ImageModalLocalizer();