//Autogenerated
import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class WidgetContainerLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly qrWidgetScanErrorLanguageItemName: string = `QrWidget.Scan.Error`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "fi", label: "Suomi" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" }
            ],
            "en");
        
        //Initializer
        this.set(this.qrWidgetScanErrorLanguageItemName, { language: `en`, value: `` },);
    }

    /**
    /* "QrWidget.Scan.Error" ()
    */
    public get qrWidgetScanError() : string {
        return this.get(this.qrWidgetScanErrorLanguageItemName);
    }
}

//Singleton
export default new WidgetContainerLocalizer();