//Autogenerated

import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class ImageEditorLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly saveLanguageItemName: string = `Save`;
    public readonly browseLanguageItemName: string = `Browse`;
    public readonly rotateLeftLanguageItemName: string = `RotateLeft`;
    public readonly rotateRightLanguageItemName: string = `RotateRight`;
    public readonly deleteLanguageItemName: string = `Delete`;
    public readonly editLanguageItemName: string = `Edit`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "da", label: "Dansk" },
                { code: "fi", label: "Suomi" },
                { code: "nb", label: "Norsk bokmål" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська" }
            ],
            "en");
        
        //Initializer
        this.set(this.saveLanguageItemName, { language: `en`, value: `Save` },);
        this.set(this.browseLanguageItemName, { language: `en`, value: `Browse` },);
        this.set(this.rotateLeftLanguageItemName, { language: `en`, value: `Rotate left` },);
        this.set(this.rotateRightLanguageItemName, { language: `en`, value: `Rotate right` },);
        this.set(this.deleteLanguageItemName, { language: `en`, value: `Delete` },);
        this.set(this.editLanguageItemName, { language: `en`, value: `Edit` },);
    }

    /**
    /* "Save" (Save)
    */
    public get save() : string {
        return this.get(this.saveLanguageItemName);
    }

    /**
    /* "Browse" (Browse)
    */
    public get browse() : string {
        return this.get(this.browseLanguageItemName);
    }

    /**
    /* "RotateLeft" (Rotate left)
    */
    public get rotateLeft() : string {
        return this.get(this.rotateLeftLanguageItemName);
    }

    /**
    /* "RotateRight" (Rotate right)
    */
    public get rotateRight() : string {
        return this.get(this.rotateRightLanguageItemName);
    }

    /**
    /* "Delete" (Delete)
    */
    public get delete() : string {
        return this.get(this.deleteLanguageItemName);
    }

    /**
    /* "Edit" (Edit)
    */
    public get edit() : string {
        return this.get(this.editLanguageItemName);
    }
}

//Singleton
export default new ImageEditorLocalizer();