//Autogenerated

import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class QrWidgetLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly scanErrorLanguageItemName: string = `Scan.Error`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "fi", label: "Suomi" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська" }
            ],
            "en");
        
        //Initializer
        this.set(this.scanErrorLanguageItemName, { language: `en`, value: `QR code scanner is not available, probably no permissions to camera on your mobile device.` }, { language: `uk`, value: `UK-UA: QR code scanner is not available, probably no permissions to camera on your mobile device.` }, { language: `sv`, value: `QR-kodskanner inte tillgänglig, förmodligen inga behörigheter för kameran på din mobila enhet.` }, { language: `ru`, value: `RU: QR code scanner not available, probably no permissions to camera on you mobile device.` }, { language: `pl`, value: `PL: QR code scanner not available, probably no permissions to camera on you mobile device.` }, { language: `fi`, value: `QR koodi skanneri ei käytössä. Mahdollisesti kameran käyttöoikeudet puuttuvat laitteeltasi.` },);
    }

    /**
    /* "Scan.Error" (QR code scanner is not available, probably no permissions to camera on your mobile device.)
    */
    public get scanError() : string {
        return this.get(this.scanErrorLanguageItemName);
    }
}

//Singleton
export default new QrWidgetLocalizer();