//Autogenerated

import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class NumberWidgetLocalizer extends BaseComponentLocalizer {

    //Constants


    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "da", label: "Dansk" },
                { code: "fi", label: "Suomi" },
                { code: "nb", label: "Norsk bokmål" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська" }
            ],
            "en");
        
        //Initializer

    }


}

//Singleton
export default new NumberWidgetLocalizer();