//Autogenerated

import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class FooterLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly frontpageLanguageItemName: string = `Frontpage`;
    public readonly contactLanguageItemName: string = `Contact`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "da", label: "Dansk" },
                { code: "fi", label: "Suomi" },
                { code: "nb", label: "Norsk bokmål" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська" }
            ],
            "en");
        
        //Initializer
        this.set(this.frontpageLanguageItemName, { language: `en`, value: `Frontpage` }, { language: `uk`, value: `UK: Frontpage` }, { language: `sv`, value: `Framsida` }, { language: `ru`, value: `RU: Frontpage` }, { language: `pl`, value: `Strona główna` }, { language: `nb`, value: `Hjemmeside` }, { language: `fi`, value: `Etusivu` }, { language: `da`, value: `Forside` },);
        this.set(this.contactLanguageItemName, { language: `en`, value: `Contact information` }, { language: `uk`, value: `UK: Contact information` }, { language: `sv`, value: `Kontakt information` }, { language: `ru`, value: `RU: Contact information` }, { language: `pl`, value: `Informacje kontaktowe` }, { language: `nb`, value: `Kontakt informasjon` }, { language: `fi`, value: `Yhteystiedot` }, { language: `da`, value: `Kontaktinformation` },);
    }

    /**
    /* "Frontpage" (Frontpage)
    */
    public get frontpage() : string {
        return this.get(this.frontpageLanguageItemName);
    }

    /**
    /* "Contact" (Contact information)
    */
    public get contact() : string {
        return this.get(this.contactLanguageItemName);
    }
}

//Singleton
export default new FooterLocalizer();