//Autogenerated
import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class FooterLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly contactLanguageItemName: string = `Contact`;
    public readonly frontpageLanguageItemName: string = `Frontpage`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "fi", label: "Suomi" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" }
            ],
            "en");
        
        //Initializer
        this.set(this.contactLanguageItemName, { language: `en`, value: `Contact information` }, { language: `sv`, value: `Kontakt information` }, { language: `ru`, value: `RU: Contact information` }, { language: `pl`, value: `PL: Contact information` }, { language: `fi`, value: `Yhteystiedot` },);
        this.set(this.frontpageLanguageItemName, { language: `en`, value: `Frontpage` }, { language: `sv`, value: `Framsida` }, { language: `ru`, value: `RU: Frontpage` }, { language: `pl`, value: `PL: Frontpage` }, { language: `fi`, value: `Etusivu` },);
    }

    /**
    /* "Contact" (Contact information)
    */
    public get contact() : string {
        return this.get(this.contactLanguageItemName);
    }

    /**
    /* "Frontpage" (Frontpage)
    */
    public get frontpage() : string {
        return this.get(this.frontpageLanguageItemName);
    }
}

//Singleton
export default new FooterLocalizer();