//Autogenerated

import {BaseComponentLocalizer} from "@weare/athenaeum-react-common";

class FileInputLocalizer extends BaseComponentLocalizer {

    //Constants
    public readonly dragAndDropLanguageItemName: string = `DragAndDrop`;
    public readonly readonlyLanguageItemName: string = `Readonly`;
    public readonly chooseFileLanguageItemName: string = `ChooseFile`;
    public readonly previewLanguageItemName: string = `Preview`;

    constructor() {

        super(
            [
                { code: "en", label: "English" },
                { code: "da", label: "Dansk" },
                { code: "fi", label: "Suomi" },
                { code: "nb", label: "Norsk bokmål" },
                { code: "pl", label: "Polski" },
                { code: "ru", label: "Русский" },
                { code: "sv", label: "Svenska" },
                { code: "uk", label: "Українська" }
            ],
            "en");
        
        //Initializer
        this.set(this.dragAndDropLanguageItemName, { language: `en`, value: `Drag'n'drop file here, or click to select` }, { language: `uk`, value: `Перетягніть файл, або оберіть його` }, { language: `sv`, value: `Släpp filen här eller välj genom att trycka` }, { language: `ru`, value: `RU: Drag'n'drop file here, or click to select` }, { language: `pl`, value: `Przeciągnij pliki tutaj i upuść albo kliknij aby wybrać` }, { language: `nb`, value: `Dra og drop filen hit, eller klikk for å velge` }, { language: `fi`, value: `Pudota tiedosto tähän tai valitse klikkaamalla` }, { language: `da`, value: `Placer filen her, eller vælg ved at klikke` },);
        this.set(this.readonlyLanguageItemName, { language: `en`, value: `File is readonly` }, { language: `uk`, value: `UK: File is readonly` }, { language: `sv`, value: `Filen är bara läsbar` }, { language: `ru`, value: `RU: File is readonly` }, { language: `pl`, value: `Plik tylko do odczytu` }, { language: `nb`, value: `NB: File is readonly` }, { language: `fi`, value: `Tämä tiedosto on vain luettavissa` }, { language: `da`, value: `DA: File is readonly` },);
        this.set(this.chooseFileLanguageItemName, { language: `en`, value: `Choose file` }, { language: `uk`, value: `Оберіть файл` }, { language: `sv`, value: `Välj fil` }, { language: `ru`, value: `RU: Choose file` }, { language: `pl`, value: `Wybierz plik` }, { language: `nb`, value: `Velg fil` }, { language: `fi`, value: `Valitse tiedosto` }, { language: `da`, value: `Vælg fil` },);
        this.set(this.previewLanguageItemName, { language: `en`, value: `Preview` }, { language: `uk`, value: `Переглянути` }, { language: `sv`, value: `Förhandsvisning` }, { language: `ru`, value: `RU: Preview` }, { language: `pl`, value: `Podgląd` }, { language: `nb`, value: `NB: Preview` }, { language: `fi`, value: `Esikatselu` }, { language: `da`, value: `DA: Preview` },);
    }

    /**
    /* "DragAndDrop" (Drag'n'drop file here, or click to select)
    */
    public get dragAndDrop() : string {
        return this.get(this.dragAndDropLanguageItemName);
    }

    /**
    /* "Readonly" (File is readonly)
    */
    public get readonly() : string {
        return this.get(this.readonlyLanguageItemName);
    }

    /**
    /* "ChooseFile" (Choose file)
    */
    public get chooseFile() : string {
        return this.get(this.chooseFileLanguageItemName);
    }

    /**
    /* "Preview" (Preview)
    */
    public get preview() : string {
        return this.get(this.previewLanguageItemName);
    }
}

//Singleton
export default new FileInputLocalizer();